// Mocks generated by Mockito 5.4.5 from annotations
// in jfit/test/core/bloc/bloc_communication_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:jfit/core/error/failures.dart' as _i5;
import 'package:jfit/features/daily_summary/data/repositories/daily_summary_repository.dart'
    as _i7;
import 'package:jfit/features/meal/data/repositories/meal_repository.dart'
    as _i3;
import 'package:jfit/features/programs/data/models/user_program_day_model.dart'
    as _i13;
import 'package:jfit/features/programs/data/models/workout_session_model.dart'
    as _i10;
import 'package:jfit/features/records/data/models/meal_record_model.dart'
    as _i6;
import 'package:jfit/features/records/data/models/user_daily_summary_model.dart'
    as _i8;
import 'package:jfit/features/workout_program/data/models/current_workout_info_model.dart'
    as _i14;
import 'package:jfit/features/workout_program/data/models/user_program_model.dart'
    as _i12;
import 'package:jfit/features/workout_program/data/repositories/workout_program_repository.dart'
    as _i11;
import 'package:jfit/features/workout_session/data/repositories/workout_session_repository.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MealRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealRepository extends _i1.Mock implements _i3.MealRepository {
  MockMealRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.MealRecord>>> getMealRecords(
    String? userId, {
    DateTime? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMealRecords,
          [userId],
          {#date: date},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.MealRecord>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.MealRecord>>(
          this,
          Invocation.method(
            #getMealRecords,
            [userId],
            {#date: date},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.MealRecord>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addMealRecord(
          _i6.MealRecord? record) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMealRecord,
          [record],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #addMealRecord,
            [record],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateMealRecord(
          _i6.MealRecord? record) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMealRecord,
          [record],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateMealRecord,
            [record],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteMealRecord(
          String? recordId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMealRecord,
          [recordId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteMealRecord,
            [recordId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, T>> safeCall<T>(
          _i4.Future<T> Function()? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #safeCall,
          [operation],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, T>>.value(
            _FakeEither_0<_i5.Failure, T>(
          this,
          Invocation.method(
            #safeCall,
            [operation],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, T>>);
}

/// A class which mocks [DailySummaryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDailySummaryRepository extends _i1.Mock
    implements _i7.DailySummaryRepository {
  MockDailySummaryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.UserDailySummary?>> getDailySummary(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDailySummary,
          [
            userId,
            date,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i8.UserDailySummary?>>.value(
                _FakeEither_0<_i5.Failure, _i8.UserDailySummary?>(
          this,
          Invocation.method(
            #getDailySummary,
            [
              userId,
              date,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.UserDailySummary?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.UserDailySummary>> upsertDailySummary(
          _i8.UserDailySummary? summary) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertDailySummary,
          [summary],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i8.UserDailySummary>>.value(
                _FakeEither_0<_i5.Failure, _i8.UserDailySummary>(
          this,
          Invocation.method(
            #upsertDailySummary,
            [summary],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.UserDailySummary>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.UserDailySummary>>>
      getDailySummariesForRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getDailySummariesForRange,
              [
                userId,
                startDate,
                endDate,
              ],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i8.UserDailySummary>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.UserDailySummary>>(
              this,
              Invocation.method(
                #getDailySummariesForRange,
                [
                  userId,
                  startDate,
                  endDate,
                ],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.UserDailySummary>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.UserDailySummary>>
      calculateAndUpdateDailySummary(
    String? userId,
    DateTime? date,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #calculateAndUpdateDailySummary,
              [
                userId,
                date,
              ],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i8.UserDailySummary>>.value(
                    _FakeEither_0<_i5.Failure, _i8.UserDailySummary>(
              this,
              Invocation.method(
                #calculateAndUpdateDailySummary,
                [
                  userId,
                  date,
                ],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i8.UserDailySummary>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteDailySummary(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDailySummary,
          [
            userId,
            date,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteDailySummary,
            [
              userId,
              date,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, T>> safeCall<T>(
          _i4.Future<T> Function()? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #safeCall,
          [operation],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, T>>.value(
            _FakeEither_0<_i5.Failure, T>(
          this,
          Invocation.method(
            #safeCall,
            [operation],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, T>>);

  @override
  _i4.Future<bool> validateUserAccess(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #validateUserAccess,
          [userId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<T>>> getDataForDateRange<T>(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDataForDateRange,
          [
            userId,
            startDate,
            endDate,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<T>>>.value(
            _FakeEither_0<_i5.Failure, List<T>>(
          this,
          Invocation.method(
            #getDataForDateRange,
            [
              userId,
              startDate,
              endDate,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<T>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<T>>> getDataForDate<T>(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDataForDate,
          [
            userId,
            date,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<T>>>.value(
            _FakeEither_0<_i5.Failure, List<T>>(
          this,
          Invocation.method(
            #getDataForDate,
            [
              userId,
              date,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<T>>>);
}

/// A class which mocks [WorkoutSessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutSessionRepository extends _i1.Mock
    implements _i9.WorkoutSessionRepository {
  MockWorkoutSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> createWorkoutSession({
    required String? userProgramId,
    required Map<String, dynamic>? exercisesJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWorkoutSession,
          [],
          {
            #userProgramId: userProgramId,
            #exercisesJson: exercisesJson,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #createWorkoutSession,
            [],
            {
              #userProgramId: userProgramId,
              #exercisesJson: exercisesJson,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i10.WorkoutSessionModel?>>
      getWorkoutSession(String? sessionId) => (super.noSuchMethod(
            Invocation.method(
              #getWorkoutSession,
              [sessionId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i10.WorkoutSessionModel?>>.value(
                _FakeEither_0<_i5.Failure, _i10.WorkoutSessionModel?>(
              this,
              Invocation.method(
                #getWorkoutSession,
                [sessionId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i10.WorkoutSessionModel?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i10.WorkoutSessionModel>>>
      getWorkoutSessions(String? userId) => (super.noSuchMethod(
            Invocation.method(
              #getWorkoutSessions,
              [userId],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i10.WorkoutSessionModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i10.WorkoutSessionModel>>(
              this,
              Invocation.method(
                #getWorkoutSessions,
                [userId],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i10.WorkoutSessionModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i10.WorkoutSessionModel>>>
      getActiveWorkoutSessions(String? userId) => (super.noSuchMethod(
            Invocation.method(
              #getActiveWorkoutSessions,
              [userId],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i10.WorkoutSessionModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i10.WorkoutSessionModel>>(
              this,
              Invocation.method(
                #getActiveWorkoutSessions,
                [userId],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i10.WorkoutSessionModel>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i10.WorkoutSessionModel>> updateWorkoutSession({
    required String? sessionId,
    required Map<String, dynamic>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkoutSession,
          [],
          {
            #sessionId: sessionId,
            #updates: updates,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i10.WorkoutSessionModel>>.value(
                _FakeEither_0<_i5.Failure, _i10.WorkoutSessionModel>(
          this,
          Invocation.method(
            #updateWorkoutSession,
            [],
            {
              #sessionId: sessionId,
              #updates: updates,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i10.WorkoutSessionModel>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i10.WorkoutSessionModel>> completeWorkoutSession(
          String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeWorkoutSession,
          [sessionId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i10.WorkoutSessionModel>>.value(
                _FakeEither_0<_i5.Failure, _i10.WorkoutSessionModel>(
          this,
          Invocation.method(
            #completeWorkoutSession,
            [sessionId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i10.WorkoutSessionModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> logWorkoutSet({
    required String? sessionId,
    required String? exerciseId,
    required int? setNumber,
    required int? reps,
    required double? weight,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logWorkoutSet,
          [],
          {
            #sessionId: sessionId,
            #exerciseId: exerciseId,
            #setNumber: setNumber,
            #reps: reps,
            #weight: weight,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #logWorkoutSet,
            [],
            {
              #sessionId: sessionId,
              #exerciseId: exerciseId,
              #setNumber: setNumber,
              #reps: reps,
              #weight: weight,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>?>>
      getLastWorkoutLogByExercise({
    required String? exerciseId,
    required String? userId,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getLastWorkoutLogByExercise,
              [],
              {
                #exerciseId: exerciseId,
                #userId: userId,
              },
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, Map<String, dynamic>?>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>?>(
              this,
              Invocation.method(
                #getLastWorkoutLogByExercise,
                [],
                {
                  #exerciseId: exerciseId,
                  #userId: userId,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> getOrCreateExerciseId(
          String? exerciseName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrCreateExerciseId,
          [exerciseName],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #getOrCreateExerciseId,
            [exerciseName],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, T>> safeCall<T>(
          _i4.Future<T> Function()? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #safeCall,
          [operation],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, T>>.value(
            _FakeEither_0<_i5.Failure, T>(
          this,
          Invocation.method(
            #safeCall,
            [operation],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, T>>);
}

/// A class which mocks [WorkoutProgramRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutProgramRepository extends _i1.Mock
    implements _i11.WorkoutProgramRepository {
  MockWorkoutProgramRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i12.UserProgramModel>>> getUserPrograms(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPrograms,
          [userId],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<_i12.UserProgramModel>>>.value(
            _FakeEither_0<_i5.Failure, List<_i12.UserProgramModel>>(
          this,
          Invocation.method(
            #getUserPrograms,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i12.UserProgramModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i12.UserProgramModel?>>
      getUserProgramDetails(String? userProgramId) => (super.noSuchMethod(
            Invocation.method(
              #getUserProgramDetails,
              [userProgramId],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i12.UserProgramModel?>>.value(
                _FakeEither_0<_i5.Failure, _i12.UserProgramModel?>(
              this,
              Invocation.method(
                #getUserProgramDetails,
                [userProgramId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i12.UserProgramModel?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i13.UserProgramDayModel>>>
      getUserProgramDays(String? userProgramId) => (super.noSuchMethod(
            Invocation.method(
              #getUserProgramDays,
              [userProgramId],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i13.UserProgramDayModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i13.UserProgramDayModel>>(
              this,
              Invocation.method(
                #getUserProgramDays,
                [userProgramId],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i13.UserProgramDayModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateUserProgramProgress(
    String? userProgramId,
    int? currentWeek,
    int? currentDay,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProgramProgress,
          [
            userProgramId,
            currentWeek,
            currentDay,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateUserProgramProgress,
            [
              userProgramId,
              currentWeek,
              currentDay,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> completeUserProgramDay(
    String? userProgramId,
    int? week,
    int? day, {
    String? note,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeUserProgramDay,
          [
            userProgramId,
            week,
            day,
          ],
          {#note: note},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #completeUserProgramDay,
            [
              userProgramId,
              week,
              day,
            ],
            {#note: note},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteUserProgram(
          String? userProgramId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserProgram,
          [userProgramId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteUserProgram,
            [userProgramId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i14.CurrentWorkoutInfoModel>>
      getCurrentWorkoutInfo(String? userId) => (super.noSuchMethod(
            Invocation.method(
              #getCurrentWorkoutInfo,
              [userId],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, _i14.CurrentWorkoutInfoModel>>.value(
                _FakeEither_0<_i5.Failure, _i14.CurrentWorkoutInfoModel>(
              this,
              Invocation.method(
                #getCurrentWorkoutInfo,
                [userId],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, _i14.CurrentWorkoutInfoModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i12.UserProgramModel?>>
      getLatestActiveUserProgram(String? userId) => (super.noSuchMethod(
            Invocation.method(
              #getLatestActiveUserProgram,
              [userId],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i12.UserProgramModel?>>.value(
                _FakeEither_0<_i5.Failure, _i12.UserProgramModel?>(
              this,
              Invocation.method(
                #getLatestActiveUserProgram,
                [userId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i12.UserProgramModel?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, T>> safeCall<T>(
          _i4.Future<T> Function()? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #safeCall,
          [operation],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, T>>.value(
            _FakeEither_0<_i5.Failure, T>(
          this,
          Invocation.method(
            #safeCall,
            [operation],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, T>>);
}
