// Mocks generated by Mockito 5.4.6 from annotations
// in jfit/test/features/workout_session/presentation/workout_session_data_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:jfit/core/error/failures.dart' as _i5;
import 'package:jfit/features/programs/data/models/workout_session_model.dart'
    as _i6;
import 'package:jfit/features/workout_session/data/repositories/workout_session_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WorkoutSessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutSessionRepository extends _i1.Mock
    implements _i3.WorkoutSessionRepository {
  MockWorkoutSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> createWorkoutSession({
    required String? userProgramId,
    required Map<String, dynamic>? exercisesJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createWorkoutSession, [], {
              #userProgramId: userProgramId,
              #exercisesJson: exercisesJson,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#createWorkoutSession, [], {
                  #userProgramId: userProgramId,
                  #exercisesJson: exercisesJson,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WorkoutSessionModel?>>
  getWorkoutSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutSession, [sessionId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.WorkoutSessionModel?>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.WorkoutSessionModel?>(
                    this,
                    Invocation.method(#getWorkoutSession, [sessionId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.WorkoutSessionModel?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutSessionModel>>>
  getWorkoutSessions(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutSessions, [userId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.WorkoutSessionModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.WorkoutSessionModel>>(
                    this,
                    Invocation.method(#getWorkoutSessions, [userId]),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.Failure, List<_i6.WorkoutSessionModel>>
          >);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutSessionModel>>>
  getActiveWorkoutSessions(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveWorkoutSessions, [userId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.WorkoutSessionModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.WorkoutSessionModel>>(
                    this,
                    Invocation.method(#getActiveWorkoutSessions, [userId]),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.Failure, List<_i6.WorkoutSessionModel>>
          >);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WorkoutSessionModel>>
  updateWorkoutSession({
    required String? sessionId,
    required Map<String, dynamic>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkoutSession, [], {
              #sessionId: sessionId,
              #updates: updates,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.WorkoutSessionModel>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.WorkoutSessionModel>(
                    this,
                    Invocation.method(#updateWorkoutSession, [], {
                      #sessionId: sessionId,
                      #updates: updates,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.WorkoutSessionModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WorkoutSessionModel>>
  completeWorkoutSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#completeWorkoutSession, [sessionId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.WorkoutSessionModel>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.WorkoutSessionModel>(
                    this,
                    Invocation.method(#completeWorkoutSession, [sessionId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.WorkoutSessionModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> logWorkoutSet({
    required String? sessionId,
    required String? exerciseId,
    required int? setNumber,
    required int? reps,
    required double? weight,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logWorkoutSet, [], {
              #sessionId: sessionId,
              #exerciseId: exerciseId,
              #setNumber: setNumber,
              #reps: reps,
              #weight: weight,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#logWorkoutSet, [], {
                  #sessionId: sessionId,
                  #exerciseId: exerciseId,
                  #setNumber: setNumber,
                  #reps: reps,
                  #weight: weight,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>?>>
  getLastWorkoutLogByExercise({
    required String? exerciseId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLastWorkoutLogByExercise, [], {
              #exerciseId: exerciseId,
              #userId: userId,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, Map<String, dynamic>?>
                >.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>?>(
                    this,
                    Invocation.method(#getLastWorkoutLogByExercise, [], {
                      #exerciseId: exerciseId,
                      #userId: userId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> getOrCreateExerciseId(
    String? exerciseName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateExerciseId, [exerciseName]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#getOrCreateExerciseId, [exerciseName]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, T>> safeCall<T>(
    _i4.Future<T> Function()? operation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#safeCall, [operation]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, T>>.value(
              _FakeEither_0<_i5.Failure, T>(
                this,
                Invocation.method(#safeCall, [operation]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, T>>);
}
