// Mocks generated by Mockito 5.4.6 from annotations
// in jfit/test/features/daily_summary/bloc/daily_summary_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:jfit/core/error/failures.dart' as _i5;
import 'package:jfit/features/daily_summary/data/repositories/daily_summary_repository.dart'
    as _i3;
import 'package:jfit/features/records/data/models/user_daily_summary_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DailySummaryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDailySummaryRepository extends _i1.Mock
    implements _i3.DailySummaryRepository {
  MockDailySummaryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserDailySummary?>> getDailySummary(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailySummary, [userId, date]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.UserDailySummary?>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.UserDailySummary?>(
                    this,
                    Invocation.method(#getDailySummary, [userId, date]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.UserDailySummary?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserDailySummary>> upsertDailySummary(
    _i6.UserDailySummary? summary,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsertDailySummary, [summary]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.UserDailySummary>>.value(
                  _FakeEither_0<_i5.Failure, _i6.UserDailySummary>(
                    this,
                    Invocation.method(#upsertDailySummary, [summary]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.UserDailySummary>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.UserDailySummary>>>
  getDailySummariesForRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailySummariesForRange, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.UserDailySummary>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.UserDailySummary>>(
                    this,
                    Invocation.method(#getDailySummariesForRange, [
                      userId,
                      startDate,
                      endDate,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.UserDailySummary>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserDailySummary>>
  calculateAndUpdateDailySummary(String? userId, DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#calculateAndUpdateDailySummary, [userId, date]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.UserDailySummary>>.value(
                  _FakeEither_0<_i5.Failure, _i6.UserDailySummary>(
                    this,
                    Invocation.method(#calculateAndUpdateDailySummary, [
                      userId,
                      date,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.UserDailySummary>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteDailySummary(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDailySummary, [userId, date]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteDailySummary, [userId, date]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, T>> safeCall<T>(
    _i4.Future<T> Function()? operation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#safeCall, [operation]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, T>>.value(
              _FakeEither_0<_i5.Failure, T>(
                this,
                Invocation.method(#safeCall, [operation]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, T>>);

  @override
  _i4.Future<bool> validateUserAccess(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#validateUserAccess, [userId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<T>>> getDataForDateRange<T>(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDataForDateRange, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, List<T>>>.value(
              _FakeEither_0<_i5.Failure, List<T>>(
                this,
                Invocation.method(#getDataForDateRange, [
                  userId,
                  startDate,
                  endDate,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<T>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<T>>> getDataForDate<T>(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDataForDate, [userId, date]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, List<T>>>.value(
              _FakeEither_0<_i5.Failure, List<T>>(
                this,
                Invocation.method(#getDataForDate, [userId, date]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<T>>>);
}
