// Mocks generated by Mockito 5.4.5 from annotations
// in jfit/test/features/meal/bloc/meal_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:jfit/core/error/failures.dart' as _i5;
import 'package:jfit/features/meal/data/repositories/meal_repository.dart'
    as _i3;
import 'package:jfit/features/records/data/models/meal_record_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MealRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealRepository extends _i1.Mock implements _i3.MealRepository {
  MockMealRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.MealRecord>>> getMealRecords(
    String? userId, {
    DateTime? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMealRecords,
          [userId],
          {#date: date},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.MealRecord>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.MealRecord>>(
          this,
          Invocation.method(
            #getMealRecords,
            [userId],
            {#date: date},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.MealRecord>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addMealRecord(
          _i6.MealRecord? record) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMealRecord,
          [record],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #addMealRecord,
            [record],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateMealRecord(
          _i6.MealRecord? record) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMealRecord,
          [record],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateMealRecord,
            [record],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteMealRecord(
          String? recordId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMealRecord,
          [recordId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteMealRecord,
            [recordId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, T>> safeCall<T>(
          _i4.Future<T> Function()? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #safeCall,
          [operation],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, T>>.value(
            _FakeEither_0<_i5.Failure, T>(
          this,
          Invocation.method(
            #safeCall,
            [operation],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, T>>);
}
