// Mocks generated by Mockito 5.4.5 from annotations
// in jfit/test/features/group_workout_community/presentation/widgets/group_chat_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:jfit/core/error/failures.dart' as _i5;
import 'package:jfit/features/group_workout_community/domain/entities/group_message.dart'
    as _i6;
import 'package:jfit/features/group_workout_community/domain/repositories/group_chat_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GroupChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupChatRepository extends _i1.Mock
    implements _i3.GroupChatRepository {
  MockGroupChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>> getGroupMessages(
    String? groupId, {
    int? limit = 50,
    int? offset = 0,
    DateTime? before,
    DateTime? after,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupMessages,
          [groupId],
          {
            #limit: limit,
            #offset: offset,
            #before: before,
            #after: after,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.GroupMessage>>(
          this,
          Invocation.method(
            #getGroupMessages,
            [groupId],
            {
              #limit: limit,
              #offset: offset,
              #before: before,
              #after: after,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.GroupMessage>> sendMessage(
          _i3.SendMessageRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.GroupMessage>>.value(
                _FakeEither_0<_i5.Failure, _i6.GroupMessage>(
          this,
          Invocation.method(
            #sendMessage,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.GroupMessage>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.GroupMessage>> updateMessage(
    _i3.UpdateMessageRequest? request,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMessage,
          [
            request,
            userId,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.GroupMessage>>.value(
                _FakeEither_0<_i5.Failure, _i6.GroupMessage>(
          this,
          Invocation.method(
            #updateMessage,
            [
              request,
              userId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.GroupMessage>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteMessage(
    String? messageId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMessage,
          [
            messageId,
            userId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteMessage,
            [
              messageId,
              userId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addMessageReaction(
          _i3.MessageReactionRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMessageReaction,
          [request],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #addMessageReaction,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeMessageReaction(
          _i3.MessageReactionRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMessageReaction,
          [request],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #removeMessageReaction,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, List<String>>>>
      getMessageReactions(String? messageId) => (super.noSuchMethod(
            Invocation.method(
              #getMessageReactions,
              [messageId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, Map<String, List<String>>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, List<String>>>(
              this,
              Invocation.method(
                #getMessageReactions,
                [messageId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, List<String>>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.GroupMessage?>> getMessageById(
          String? messageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessageById,
          [messageId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.GroupMessage?>>.value(
                _FakeEither_0<_i5.Failure, _i6.GroupMessage?>(
          this,
          Invocation.method(
            #getMessageById,
            [messageId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.GroupMessage?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>> searchMessages(
    String? groupId,
    String? query, {
    _i6.MessageType? messageType,
    DateTime? startDate,
    DateTime? endDate,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMessages,
          [
            groupId,
            query,
          ],
          {
            #messageType: messageType,
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.GroupMessage>>(
          this,
          Invocation.method(
            #searchMessages,
            [
              groupId,
              query,
            ],
            {
              #messageType: messageType,
              #startDate: startDate,
              #endDate: endDate,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>> getMessageThread(
          String? messageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessageThread,
          [messageId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.GroupMessage>>(
          this,
          Invocation.method(
            #getMessageThread,
            [messageId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> markMessagesAsRead(
    String? groupId,
    String? userId,
    List<String>? messageIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMessagesAsRead,
          [
            groupId,
            userId,
            messageIds,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #markMessagesAsRead,
            [
              groupId,
              userId,
              messageIds,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getUnreadMessageCount(
    String? groupId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnreadMessageCount,
          [
            groupId,
            userId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #getUnreadMessageCount,
            [
              groupId,
              userId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>> getRecentMessages(
    String? userId, {
    int? limit = 20,
    int? hours = 24,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentMessages,
          [userId],
          {
            #limit: limit,
            #hours: hours,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.GroupMessage>>(
          this,
          Invocation.method(
            #getRecentMessages,
            [userId],
            {
              #limit: limit,
              #hours: hours,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> sendTypingIndicator(
    String? groupId,
    String? userId,
    bool? isTyping,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendTypingIndicator,
          [
            groupId,
            userId,
            isTyping,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #sendTypingIndicator,
            [
              groupId,
              userId,
              isTyping,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>
      getTypingUsers(String? groupId) => (super.noSuchMethod(
            Invocation.method(
              #getTypingUsers,
              [groupId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<Map<String, dynamic>>>>.value(
                _FakeEither_0<_i5.Failure, List<Map<String, dynamic>>>(
              this,
              Invocation.method(
                #getTypingUsers,
                [groupId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.GroupMessage>> sendImageMessage(
    String? groupId,
    String? senderId,
    String? imagePath,
    String? caption,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendImageMessage,
          [
            groupId,
            senderId,
            imagePath,
            caption,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.GroupMessage>>.value(
                _FakeEither_0<_i5.Failure, _i6.GroupMessage>(
          this,
          Invocation.method(
            #sendImageMessage,
            [
              groupId,
              senderId,
              imagePath,
              caption,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.GroupMessage>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.GroupMessage>> shareWorkout(
    String? groupId,
    String? senderId,
    String? workoutId,
    String? workoutDescription,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareWorkout,
          [
            groupId,
            senderId,
            workoutId,
            workoutDescription,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.GroupMessage>>.value(
                _FakeEither_0<_i5.Failure, _i6.GroupMessage>(
          this,
          Invocation.method(
            #shareWorkout,
            [
              groupId,
              senderId,
              workoutId,
              workoutDescription,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.GroupMessage>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> getGroupChatStats(
    String? groupId, {
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupChatStats,
          [groupId],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #getGroupChatStats,
            [groupId],
            {
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> pinMessage(
    String? messageId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #pinMessage,
          [
            messageId,
            userId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #pinMessage,
            [
              messageId,
              userId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> unpinMessage(
    String? messageId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unpinMessage,
          [
            messageId,
            userId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #unpinMessage,
            [
              messageId,
              userId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>> getPinnedMessages(
          String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPinnedMessages,
          [groupId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.GroupMessage>>(
          this,
          Invocation.method(
            #getPinnedMessages,
            [groupId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> reportMessage(
    String? messageId,
    String? reporterId,
    String? reason,
    String? description,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportMessage,
          [
            messageId,
            reporterId,
            reason,
            description,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #reportMessage,
            [
              messageId,
              reporterId,
              reason,
              description,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i6.GroupMessage>>> getUserMessageHistory(
    String? userId,
    String? groupId, {
    int? limit = 100,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserMessageHistory,
          [
            userId,
            groupId,
          ],
          {
            #limit: limit,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.GroupMessage>>(
          this,
          Invocation.method(
            #getUserMessageHistory,
            [
              userId,
              groupId,
            ],
            {
              #limit: limit,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> bulkDeleteMessages(
    List<String>? messageIds,
    String? adminId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #bulkDeleteMessages,
          [
            messageIds,
            adminId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #bulkDeleteMessages,
            [
              messageIds,
              adminId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> getMessageStatus(
          String? messageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessageStatus,
          [messageId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #getMessageStatus,
            [messageId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Stream<_i6.GroupMessage> subscribeToMessages(String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToMessages,
          [groupId],
        ),
        returnValue: _i4.Stream<_i6.GroupMessage>.empty(),
      ) as _i4.Stream<_i6.GroupMessage>);

  @override
  _i4.Stream<Map<String, dynamic>> subscribeToTypingIndicators(
          String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToTypingIndicators,
          [groupId],
        ),
        returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
      ) as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>> getUserMentions(
    String? userId, {
    String? groupId,
    bool? unreadOnly = false,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserMentions,
          [userId],
          {
            #groupId: groupId,
            #unreadOnly: unreadOnly,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.GroupMessage>>(
          this,
          Invocation.method(
            #getUserMentions,
            [userId],
            {
              #groupId: groupId,
              #unreadOnly: unreadOnly,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupMessage>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> exportChatHistory(
    String? groupId, {
    DateTime? startDate,
    DateTime? endDate,
    String? format = 'json',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportChatHistory,
          [groupId],
          {
            #startDate: startDate,
            #endDate: endDate,
            #format: format,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #exportChatHistory,
            [groupId],
            {
              #startDate: startDate,
              #endDate: endDate,
              #format: format,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, T>> safeCall<T>(
          _i4.Future<T> Function()? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #safeCall,
          [operation],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, T>>.value(
            _FakeEither_0<_i5.Failure, T>(
          this,
          Invocation.method(
            #safeCall,
            [operation],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, T>>);
}
