// Mocks generated by Mockito 5.4.5 from annotations
// in jfit/test/features/group_workout_community/presentation/widgets/group_activity_feed_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_bloc/flutter_bloc.dart' as _i10;
import 'package:jfit/core/bloc/bloc_event_bus.dart' as _i7;
import 'package:jfit/core/error/bloc_errors.dart' as _i8;
import 'package:jfit/features/group_workout_community/domain/entities/workout_group.dart'
    as _i5;
import 'package:jfit/features/group_workout_community/domain/repositories/group_activity_repository.dart'
    as _i6;
import 'package:jfit/features/group_workout_community/presentation/bloc/group_activity/group_activity_bloc.dart'
    as _i3;
import 'package:jfit/features/group_workout_community/presentation/bloc/group_activity/group_activity_event.dart'
    as _i9;
import 'package:jfit/features/group_workout_community/presentation/bloc/group_activity/group_activity_state.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGroupActivityState_0 extends _i1.SmartFake
    implements _i2.GroupActivityState {
  _FakeGroupActivityState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GroupActivityBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupActivityBloc extends _i1.Mock implements _i3.GroupActivityBloc {
  MockGroupActivityBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isActive => (super.noSuchMethod(
        Invocation.getter(#isActive),
        returnValue: false,
      ) as bool);

  @override
  _i2.GroupActivityState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeGroupActivityState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.GroupActivityState);

  @override
  _i4.Stream<_i2.GroupActivityState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i2.GroupActivityState>.empty(),
      ) as _i4.Stream<_i2.GroupActivityState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> getCacheMetrics() => (super.noSuchMethod(
        Invocation.method(
          #getCacheMetrics,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void onInactivity() => super.noSuchMethod(
        Invocation.method(
          #onInactivity,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void loadGroupActivities(
    String? groupId, {
    bool? forceRefresh = false,
    List<_i5.GroupActivityType>? activityTypes,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #loadGroupActivities,
          [groupId],
          {
            #forceRefresh: forceRefresh,
            #activityTypes: activityTypes,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void loadMoreActivities(
    String? groupId, {
    List<_i5.GroupActivityType>? activityTypes,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #loadMoreActivities,
          [groupId],
          {#activityTypes: activityTypes},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void shareRoutine(_i6.ShareRoutineRequest? request) => super.noSuchMethod(
        Invocation.method(
          #shareRoutine,
          [request],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logWorkoutCompletion(_i6.WorkoutCompletionRequest? request) =>
      super.noSuchMethod(
        Invocation.method(
          #logWorkoutCompletion,
          [request],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendEncouragement(_i6.EncouragementRequest? request) =>
      super.noSuchMethod(
        Invocation.method(
          #sendEncouragement,
          [request],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void loadSharedRoutines(
    String? groupId, {
    String? orderBy,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #loadSharedRoutines,
          [groupId],
          {#orderBy: orderBy},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void copySharedRoutine(_i6.CopyRoutineRequest? request) => super.noSuchMethod(
        Invocation.method(
          #copySharedRoutine,
          [request],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleRoutineLike(
    String? sharedRoutineId,
    String? userId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #toggleRoutineLike,
          [
            sharedRoutineId,
            userId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshActivityFeed(String? groupId) => super.noSuchMethod(
        Invocation.method(
          #refreshActivityFeed,
          [groupId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void filterActivitiesByType(
    String? groupId,
    List<_i5.GroupActivityType>? activityTypes,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #filterActivitiesByType,
          [
            groupId,
            activityTypes,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearActivityFilters(String? groupId) => super.noSuchMethod(
        Invocation.method(
          #clearActivityFilters,
          [groupId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommunicationEvent(_i7.BlocCommunicationEvent? event) =>
      super.noSuchMethod(
        Invocation.method(
          #handleCommunicationEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommunicationError(dynamic error) => super.noSuchMethod(
        Invocation.method(
          #handleCommunicationError,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitCommunicationEvent(_i7.BlocCommunicationEvent? event) =>
      super.noSuchMethod(
        Invocation.method(
          #emitCommunicationEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> safeAsyncOperation(
    _i4.Future<void> Function()? operation,
    void Function(_i8.BlocError)? onError,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #safeAsyncOperation,
          [
            operation,
            onError,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  Map<String, dynamic> getPerformanceMetrics() => (super.noSuchMethod(
        Invocation.method(
          #getPerformanceMetrics,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void add(_i9.GroupActivityEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i9.GroupActivityEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.GroupActivityState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i9.GroupActivityEvent>(
    _i10.EventHandler<E, _i2.GroupActivityState>? handler, {
    _i10.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i10.Transition<_i9.GroupActivityEvent, _i2.GroupActivityState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i10.Change<_i2.GroupActivityState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
