// Mocks generated by Mockito 5.4.6 from annotations
// in jfit/test/features/exercise/bloc/exercise_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:jfit/core/error/failures.dart' as _i5;
import 'package:jfit/core/models/exercise.dart' as _i6;
import 'package:jfit/features/exercise/data/repositories/exercise_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExerciseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRepository extends _i1.Mock
    implements _i3.ExerciseRepository {
  MockExerciseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>> search(
    String? query, {
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query], {#limit: limit}),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Exercise>>(
                    this,
                    Invocation.method(#search, [query], {#limit: limit}),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>> searchWithFilters(
    String? query,
    Map<String, dynamic>? filters, {
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchWithFilters,
              [query, filters],
              {#limit: limit},
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Exercise>>(
                    this,
                    Invocation.method(
                      #searchWithFilters,
                      [query, filters],
                      {#limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Exercise?>> getExerciseById(
    String? exerciseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseById, [exerciseId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Exercise?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Exercise?>(
                    this,
                    Invocation.method(#getExerciseById, [exerciseId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Exercise?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>> getExercisesByIds(
    List<String>? exerciseIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExercisesByIds, [exerciseIds]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Exercise>>(
                    this,
                    Invocation.method(#getExercisesByIds, [exerciseIds]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>> getPopularExercises({
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPopularExercises, [], {#limit: limit}),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Exercise>>(
                    this,
                    Invocation.method(#getPopularExercises, [], {
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>
  getExercisesByCategory(String? category, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getExercisesByCategory,
              [category],
              {#limit: limit},
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Exercise>>(
                    this,
                    Invocation.method(
                      #getExercisesByCategory,
                      [category],
                      {#limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>
  getExercisesByMuscleGroup(String? muscleGroup, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getExercisesByMuscleGroup,
              [muscleGroup],
              {#limit: limit},
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Exercise>>(
                    this,
                    Invocation.method(
                      #getExercisesByMuscleGroup,
                      [muscleGroup],
                      {#limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>
  getExercisesByEquipment(String? equipment, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getExercisesByEquipment,
              [equipment],
              {#limit: limit},
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Exercise>>(
                    this,
                    Invocation.method(
                      #getExercisesByEquipment,
                      [equipment],
                      {#limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>
  getExercisesByDifficulty(String? difficulty, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getExercisesByDifficulty,
              [difficulty],
              {#limit: limit},
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Exercise>>(
                    this,
                    Invocation.method(
                      #getExercisesByDifficulty,
                      [difficulty],
                      {#limit: limit},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Exercise>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> getExerciseCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseCategories, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
                  _FakeEither_0<_i5.Failure, List<String>>(
                    this,
                    Invocation.method(#getExerciseCategories, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> getMuscleGroups() =>
      (super.noSuchMethod(
            Invocation.method(#getMuscleGroups, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
                  _FakeEither_0<_i5.Failure, List<String>>(
                    this,
                    Invocation.method(#getMuscleGroups, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> getEquipmentTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getEquipmentTypes, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
                  _FakeEither_0<_i5.Failure, List<String>>(
                    this,
                    Invocation.method(#getEquipmentTypes, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> getDifficultyLevels() =>
      (super.noSuchMethod(
            Invocation.method(#getDifficultyLevels, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
                  _FakeEither_0<_i5.Failure, List<String>>(
                    this,
                    Invocation.method(#getDifficultyLevels, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#clearCache, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> refreshCache() =>
      (super.noSuchMethod(
            Invocation.method(#refreshCache, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#refreshCache, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, T>> safeCall<T>(
    _i4.Future<T> Function()? operation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#safeCall, [operation]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, T>>.value(
              _FakeEither_0<_i5.Failure, T>(
                this,
                Invocation.method(#safeCall, [operation]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, T>>);
}
