// Mocks generated by Mockito 5.4.5 from annotations
// in jfit/test/features/group_workout_community/presentation/bloc/ranking/ranking_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:jfit/core/error/failures.dart' as _i5;
import 'package:jfit/features/group_workout_community/domain/entities/body_part_mapping.dart'
    as _i9;
import 'package:jfit/features/group_workout_community/domain/entities/group_ranking.dart'
    as _i6;
import 'package:jfit/features/group_workout_community/domain/entities/user_workout_score.dart'
    as _i7;
import 'package:jfit/features/group_workout_community/domain/entities/workout_score_calculation.dart'
    as _i8;
import 'package:jfit/features/group_workout_community/domain/repositories/ranking_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RankingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRankingRepository extends _i1.Mock implements _i3.RankingRepository {
  MockRankingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupRanking>>> getGroupRankings(
    _i3.RankingPeriodRequest? request, {
    int? limit = 100,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupRankings,
          [request],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupRanking>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.GroupRanking>>(
          this,
          Invocation.method(
            #getGroupRankings,
            [request],
            {
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.GroupRanking>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.GroupRanking?>> getGroupRanking(
    String? groupId,
    _i3.RankingPeriodRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupRanking,
          [
            groupId,
            request,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.GroupRanking?>>.value(
                _FakeEither_0<_i5.Failure, _i6.GroupRanking?>(
          this,
          Invocation.method(
            #getGroupRanking,
            [
              groupId,
              request,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.GroupRanking?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserWorkoutScore>>> getUserScores(
    String? userId, {
    String? groupId,
    _i3.RankingPeriodRequest? period,
    int? limit = 30,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserScores,
          [userId],
          {
            #groupId: groupId,
            #period: period,
            #limit: limit,
          },
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<_i7.UserWorkoutScore>>>.value(
            _FakeEither_0<_i5.Failure, List<_i7.UserWorkoutScore>>(
          this,
          Invocation.method(
            #getUserScores,
            [userId],
            {
              #groupId: groupId,
              #period: period,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserWorkoutScore>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserWorkoutScore>>>
      getGroupMemberScores(
    String? groupId,
    _i3.RankingPeriodRequest? request, {
    int? limit = 50,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getGroupMemberScores,
              [
                groupId,
                request,
              ],
              {#limit: limit},
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i7.UserWorkoutScore>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.UserWorkoutScore>>(
              this,
              Invocation.method(
                #getGroupMemberScores,
                [
                  groupId,
                  request,
                ],
                {#limit: limit},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserWorkoutScore>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.UserWorkoutScore>> calculateUserScore(
          _i3.CalculateScoreRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateUserScore,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.UserWorkoutScore>>.value(
                _FakeEither_0<_i5.Failure, _i7.UserWorkoutScore>(
          this,
          Invocation.method(
            #calculateUserScore,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.UserWorkoutScore>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateGroupRankings(
          _i3.RankingPeriodRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGroupRankings,
          [request],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateGroupRankings,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> getScoreBreakdown(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScoreBreakdown,
          [
            userId,
            startDate,
            endDate,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #getScoreBreakdown,
            [
              userId,
              startDate,
              endDate,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>
      getUserGroupRankings(
    String? userId,
    _i3.RankingPeriodRequest? request,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getUserGroupRankings,
              [
                userId,
                request,
              ],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<Map<String, dynamic>>>>.value(
                _FakeEither_0<_i5.Failure, List<Map<String, dynamic>>>(
              this,
              Invocation.method(
                #getUserGroupRankings,
                [
                  userId,
                  request,
                ],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>
      getGroupTopPerformers(
    String? groupId,
    _i3.RankingPeriodRequest? request, {
    int? limit = 10,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getGroupTopPerformers,
              [
                groupId,
                request,
              ],
              {#limit: limit},
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<Map<String, dynamic>>>>.value(
                _FakeEither_0<_i5.Failure, List<Map<String, dynamic>>>(
              this,
              Invocation.method(
                #getGroupTopPerformers,
                [
                  groupId,
                  request,
                ],
                {#limit: limit},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.WorkoutScoreCalculation>>>
      getScoreCalculations(
    String? userId, {
    DateTime? startDate,
    DateTime? endDate,
    int? limit = 50,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getScoreCalculations,
              [userId],
              {
                #startDate: startDate,
                #endDate: endDate,
                #limit: limit,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        List<_i8.WorkoutScoreCalculation>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.WorkoutScoreCalculation>>(
              this,
              Invocation.method(
                #getScoreCalculations,
                [userId],
                {
                  #startDate: startDate,
                  #endDate: endDate,
                  #limit: limit,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, List<_i8.WorkoutScoreCalculation>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> calculateBodyBalanceScore(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateBodyBalanceScore,
          [
            userId,
            startDate,
            endDate,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
            _FakeEither_0<_i5.Failure, double>(
          this,
          Invocation.method(
            #calculateBodyBalanceScore,
            [
              userId,
              startDate,
              endDate,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, double>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> calculateVolumeScore(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateVolumeScore,
          [
            userId,
            startDate,
            endDate,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
            _FakeEither_0<_i5.Failure, double>(
          this,
          Invocation.method(
            #calculateVolumeScore,
            [
              userId,
              startDate,
              endDate,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, double>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> calculateProgressScore(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateProgressScore,
          [
            userId,
            startDate,
            endDate,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
            _FakeEither_0<_i5.Failure, double>(
          this,
          Invocation.method(
            #calculateProgressScore,
            [
              userId,
              startDate,
              endDate,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, double>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> calculateConsistencyScore(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateConsistencyScore,
          [
            userId,
            startDate,
            endDate,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
            _FakeEither_0<_i5.Failure, double>(
          this,
          Invocation.method(
            #calculateConsistencyScore,
            [
              userId,
              startDate,
              endDate,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, double>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<_i9.BodyPart, double>>>
      getBodyPartDistribution(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getBodyPartDistribution,
              [
                userId,
                startDate,
                endDate,
              ],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, Map<_i9.BodyPart, double>>>.value(
                _FakeEither_0<_i5.Failure, Map<_i9.BodyPart, double>>(
              this,
              Invocation.method(
                #getBodyPartDistribution,
                [
                  userId,
                  startDate,
                  endDate,
                ],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, Map<_i9.BodyPart, double>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>
      getGroupRankingTrends(
    String? groupId, {
    _i6.RankingPeriod? period = _i6.RankingPeriod.weekly,
    int? periodCount = 12,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getGroupRankingTrends,
              [groupId],
              {
                #period: period,
                #periodCount: periodCount,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<Map<String, dynamic>>>>.value(
                _FakeEither_0<_i5.Failure, List<Map<String, dynamic>>>(
              this,
              Invocation.method(
                #getGroupRankingTrends,
                [groupId],
                {
                  #period: period,
                  #periodCount: periodCount,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>
      getUserScoreTrends(
    String? userId, {
    String? groupId,
    _i6.RankingPeriod? period = _i6.RankingPeriod.weekly,
    int? periodCount = 12,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getUserScoreTrends,
              [userId],
              {
                #groupId: groupId,
                #period: period,
                #periodCount: periodCount,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<Map<String, dynamic>>>>.value(
                _FakeEither_0<_i5.Failure, List<Map<String, dynamic>>>(
              this,
              Invocation.method(
                #getUserScoreTrends,
                [userId],
                {
                  #groupId: groupId,
                  #period: period,
                  #periodCount: periodCount,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> compareUsers(
    String? userId1,
    String? userId2,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #compareUsers,
          [
            userId1,
            userId2,
            startDate,
            endDate,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #compareUsers,
            [
              userId1,
              userId2,
              startDate,
              endDate,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>
      getGroupPerformanceStats(
    String? groupId,
    _i3.RankingPeriodRequest? request,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getGroupPerformanceStats,
              [
                groupId,
                request,
              ],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                    _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
              this,
              Invocation.method(
                #getGroupPerformanceStats,
                [
                  groupId,
                  request,
                ],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>
      getBodyPartLeaderboard(
    _i9.BodyPart? bodyPart,
    _i3.RankingPeriodRequest? request, {
    String? groupId,
    int? limit = 20,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getBodyPartLeaderboard,
              [
                bodyPart,
                request,
              ],
              {
                #groupId: groupId,
                #limit: limit,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<Map<String, dynamic>>>>.value(
                _FakeEither_0<_i5.Failure, List<Map<String, dynamic>>>(
              this,
              Invocation.method(
                #getBodyPartLeaderboard,
                [
                  bodyPart,
                  request,
                ],
                {
                  #groupId: groupId,
                  #limit: limit,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>
      getRankingAchievements(
    _i3.RankingPeriodRequest? request, {
    String? groupId,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getRankingAchievements,
              [request],
              {#groupId: groupId},
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<Map<String, dynamic>>>>.value(
                _FakeEither_0<_i5.Failure, List<Map<String, dynamic>>>(
              this,
              Invocation.method(
                #getRankingAchievements,
                [request],
                {#groupId: groupId},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> recalculateAllScores(
    _i3.RankingPeriodRequest? request, {
    String? groupId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recalculateAllScores,
          [request],
          {#groupId: groupId},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #recalculateAllScores,
            [request],
            {#groupId: groupId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>
      getRankingConfiguration() => (super.noSuchMethod(
            Invocation.method(
              #getRankingConfiguration,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                    _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
              this,
              Invocation.method(
                #getRankingConfiguration,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateRankingConfiguration(
          Map<String, dynamic>? configuration) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRankingConfiguration,
          [configuration],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateRankingConfiguration,
            [configuration],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> getWorkoutAnalysis(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutAnalysis,
          [
            userId,
            startDate,
            endDate,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #getWorkoutAnalysis,
            [
              userId,
              startDate,
              endDate,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>
      getGroupCompetitionStatus(
    List<String>? groupIds,
    _i3.RankingPeriodRequest? request,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getGroupCompetitionStatus,
              [
                groupIds,
                request,
              ],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                    _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
              this,
              Invocation.method(
                #getGroupCompetitionStatus,
                [
                  groupIds,
                  request,
                ],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<
      _i2
      .Either<_i5.Failure, _i8.WorkoutScoreCalculation>> createScoreCalculation(
    String? userId,
    String? sessionId,
    Map<_i9.BodyPart, int>? bodyPartVolumes,
    double? totalVolume,
    int? exerciseVariety,
    int? sessionDurationMinutes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createScoreCalculation,
          [
            userId,
            sessionId,
            bodyPartVolumes,
            totalVolume,
            exerciseVariety,
            sessionDurationMinutes,
          ],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, _i8.WorkoutScoreCalculation>>.value(
            _FakeEither_0<_i5.Failure, _i8.WorkoutScoreCalculation>(
          this,
          Invocation.method(
            #createScoreCalculation,
            [
              userId,
              sessionId,
              bodyPartVolumes,
              totalVolume,
              exerciseVariety,
              sessionDurationMinutes,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.WorkoutScoreCalculation>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, T>> safeCall<T>(
          _i4.Future<T> Function()? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #safeCall,
          [operation],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, T>>.value(
            _FakeEither_0<_i5.Failure, T>(
          this,
          Invocation.method(
            #safeCall,
            [operation],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, T>>);
}
