// Mocks generated by Mockito 5.4.5 from annotations
// in jfit/test/features/group_workout_community/presentation/bloc/group/group_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:jfit/core/error/failures.dart' as _i5;
import 'package:jfit/features/group_workout_community/domain/entities/group_member.dart'
    as _i7;
import 'package:jfit/features/group_workout_community/domain/entities/group_search_criteria.dart'
    as _i8;
import 'package:jfit/features/group_workout_community/domain/entities/workout_group.dart'
    as _i6;
import 'package:jfit/features/group_workout_community/domain/repositories/group_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GroupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupRepository extends _i1.Mock implements _i3.GroupRepository {
  MockGroupRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutGroup>>> getUserGroups(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserGroups,
          [userId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutGroup>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.WorkoutGroup>>(
          this,
          Invocation.method(
            #getUserGroups,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutGroup>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutGroup>>> getPublicGroups({
    int? limit = 20,
    int? offset = 0,
    String? searchQuery,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublicGroups,
          [],
          {
            #limit: limit,
            #offset: offset,
            #searchQuery: searchQuery,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutGroup>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.WorkoutGroup>>(
          this,
          Invocation.method(
            #getPublicGroups,
            [],
            {
              #limit: limit,
              #offset: offset,
              #searchQuery: searchQuery,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutGroup>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WorkoutGroup?>> getGroupById(
          String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupById,
          [groupId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.WorkoutGroup?>>.value(
                _FakeEither_0<_i5.Failure, _i6.WorkoutGroup?>(
          this,
          Invocation.method(
            #getGroupById,
            [groupId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.WorkoutGroup?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WorkoutGroup>> createGroup(
    _i3.CreateGroupRequest? request,
    String? creatorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGroup,
          [
            request,
            creatorId,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.WorkoutGroup>>.value(
                _FakeEither_0<_i5.Failure, _i6.WorkoutGroup>(
          this,
          Invocation.method(
            #createGroup,
            [
              request,
              creatorId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.WorkoutGroup>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> joinGroup(
          _i3.JoinGroupRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinGroup,
          [request],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #joinGroup,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> leaveGroup(
    String? groupId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #leaveGroup,
          [
            groupId,
            userId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #leaveGroup,
            [
              groupId,
              userId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.GroupMember>>> getGroupMembers(
          String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupMembers,
          [groupId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i7.GroupMember>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.GroupMember>>(
          this,
          Invocation.method(
            #getGroupMembers,
            [groupId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.GroupMember>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WorkoutGroup>> updateGroupSettings(
    String? groupId,
    _i3.UpdateGroupRequest? request,
    String? adminId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGroupSettings,
          [
            groupId,
            request,
            adminId,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.WorkoutGroup>>.value(
                _FakeEither_0<_i5.Failure, _i6.WorkoutGroup>(
          this,
          Invocation.method(
            #updateGroupSettings,
            [
              groupId,
              request,
              adminId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.WorkoutGroup>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeGroupMember(
    String? groupId,
    String? memberUserId,
    String? adminId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeGroupMember,
          [
            groupId,
            memberUserId,
            adminId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #removeGroupMember,
            [
              groupId,
              memberUserId,
              adminId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateMemberRole(
    String? groupId,
    String? memberUserId,
    _i6.GroupRole? newRole,
    String? adminId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemberRole,
          [
            groupId,
            memberUserId,
            newRole,
            adminId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateMemberRole,
            [
              groupId,
              memberUserId,
              newRole,
              adminId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> transferOwnership(
    String? groupId,
    String? newAdminUserId,
    String? currentAdminId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #transferOwnership,
          [
            groupId,
            newAdminUserId,
            currentAdminId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #transferOwnership,
            [
              groupId,
              newAdminUserId,
              currentAdminId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> generateInviteCode(
    String? groupId,
    String? adminId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateInviteCode,
          [
            groupId,
            adminId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #generateInviteCode,
            [
              groupId,
              adminId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> validateInviteCode(
    String? groupId,
    String? inviteCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateInviteCode,
          [
            groupId,
            inviteCode,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #validateInviteCode,
            [
              groupId,
              inviteCode,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.GroupMember?>> getGroupMembership(
    String? groupId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupMembership,
          [
            groupId,
            userId,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.GroupMember?>>.value(
                _FakeEither_0<_i5.Failure, _i7.GroupMember?>(
          this,
          Invocation.method(
            #getGroupMembership,
            [
              groupId,
              userId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.GroupMember?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutGroup>>> getManagedGroups(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getManagedGroups,
          [userId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutGroup>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.WorkoutGroup>>(
          this,
          Invocation.method(
            #getManagedGroups,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutGroup>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deactivateGroup(
    String? groupId,
    String? adminId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deactivateGroup,
          [
            groupId,
            adminId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deactivateGroup,
            [
              groupId,
              adminId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> getGroupStats(
          String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupStats,
          [groupId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #getGroupStats,
            [groupId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutGroup>>> searchGroups({
    required _i8.GroupSearchCriteria? criteria,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchGroups,
          [],
          {
            #criteria: criteria,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutGroup>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.WorkoutGroup>>(
          this,
          Invocation.method(
            #searchGroups,
            [],
            {
              #criteria: criteria,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutGroup>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i6.WorkoutGroup>>> getSuggestedGroups(
    String? userId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSuggestedGroups,
          [userId],
          {#limit: limit},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutGroup>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.WorkoutGroup>>(
          this,
          Invocation.method(
            #getSuggestedGroups,
            [userId],
            {#limit: limit},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutGroup>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutGroup>>> getTrendingGroups(
          {int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrendingGroups,
          [],
          {#limit: limit},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutGroup>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.WorkoutGroup>>(
          this,
          Invocation.method(
            #getTrendingGroups,
            [],
            {#limit: limit},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutGroup>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, T>> safeCall<T>(
          _i4.Future<T> Function()? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #safeCall,
          [operation],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, T>>.value(
            _FakeEither_0<_i5.Failure, T>(
          this,
          Invocation.method(
            #safeCall,
            [operation],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, T>>);
}
