// Mocks generated by Mockito 5.4.5 from annotations
// in jfit/test/features/programs/presentation/bloc/programs_bloc_error_handling_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:jfit/core/error/failures.dart' as _i5;
import 'package:jfit/features/programs/data/models/exercise_model.dart' as _i11;
import 'package:jfit/features/programs/data/models/user_program_day_model.dart'
    as _i8;
import 'package:jfit/features/programs/data/models/workout_log_model.dart'
    as _i10;
import 'package:jfit/features/programs/data/models/workout_session_model.dart'
    as _i9;
import 'package:jfit/features/programs/domain/entities/workout_program.dart'
    as _i6;
import 'package:jfit/features/programs/domain/repositories/program_repository.dart'
    as _i3;
import 'package:jfit/features/workout_program/data/models/duplicate_check_result_model.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProgramRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgramRepository extends _i1.Mock implements _i3.ProgramRepository {
  MockProgramRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutProgram>>>
      getPopularPrograms() => (super.noSuchMethod(
            Invocation.method(
              #getPopularPrograms,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.WorkoutProgram>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.WorkoutProgram>>(
              this,
              Invocation.method(
                #getPopularPrograms,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutProgram>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutProgram>>> getPrograms({
    String? searchQuery,
    String? difficultyLevel,
    String? programType,
    int? workoutsPerWeek,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrograms,
          [],
          {
            #searchQuery: searchQuery,
            #difficultyLevel: difficultyLevel,
            #programType: programType,
            #workoutsPerWeek: workoutsPerWeek,
            #tags: tags,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutProgram>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.WorkoutProgram>>(
          this,
          Invocation.method(
            #getPrograms,
            [],
            {
              #searchQuery: searchQuery,
              #difficultyLevel: difficultyLevel,
              #programType: programType,
              #workoutsPerWeek: workoutsPerWeek,
              #tags: tags,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutProgram>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WorkoutProgram>> getProgramById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProgramById,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.WorkoutProgram>>.value(
                _FakeEither_0<_i5.Failure, _i6.WorkoutProgram>(
          this,
          Invocation.method(
            #getProgramById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.WorkoutProgram>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addProgramToUser(
          String? programId) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProgramToUser,
          [programId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #addProgramToUser,
            [programId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.DuplicateCheckResult>> saveAsMyRoutine(
          String? templateProgramId) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAsMyRoutine,
          [templateProgramId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.DuplicateCheckResult>>.value(
                _FakeEither_0<_i5.Failure, _i7.DuplicateCheckResult>(
          this,
          Invocation.method(
            #saveAsMyRoutine,
            [templateProgramId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.DuplicateCheckResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutProgram>>>
      getUserPrograms() => (super.noSuchMethod(
            Invocation.method(
              #getUserPrograms,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.WorkoutProgram>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.WorkoutProgram>>(
              this,
              Invocation.method(
                #getUserPrograms,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutProgram>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutProgram>>> searchPrograms(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPrograms,
          [query],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutProgram>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.WorkoutProgram>>(
          this,
          Invocation.method(
            #searchPrograms,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkoutProgram>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.UserProgramDayModel>>>
      getUserProgramDays(String? userProgramId) => (super.noSuchMethod(
            Invocation.method(
              #getUserProgramDays,
              [userProgramId],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i8.UserProgramDayModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.UserProgramDayModel>>(
              this,
              Invocation.method(
                #getUserProgramDays,
                [userProgramId],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i8.UserProgramDayModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.WorkoutSessionModel>>>
      getWorkoutSessionsByUserProgram(String? userProgramId) =>
          (super.noSuchMethod(
            Invocation.method(
              #getWorkoutSessionsByUserProgram,
              [userProgramId],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i9.WorkoutSessionModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i9.WorkoutSessionModel>>(
              this,
              Invocation.method(
                #getWorkoutSessionsByUserProgram,
                [userProgramId],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i9.WorkoutSessionModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i10.WorkoutLogModel>>>
      getWorkoutLogsBySession(String? sessionId) => (super.noSuchMethod(
            Invocation.method(
              #getWorkoutLogsBySession,
              [sessionId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i10.WorkoutLogModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i10.WorkoutLogModel>>(
              this,
              Invocation.method(
                #getWorkoutLogsBySession,
                [sessionId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i10.WorkoutLogModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i11.ExerciseModel>> getExerciseById(
          String? exerciseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExerciseById,
          [exerciseId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i11.ExerciseModel>>.value(
                _FakeEither_0<_i5.Failure, _i11.ExerciseModel>(
          this,
          Invocation.method(
            #getExerciseById,
            [exerciseId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i11.ExerciseModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>?>>
      checkProgramDuplicate(String? programId) => (super.noSuchMethod(
            Invocation.method(
              #checkProgramDuplicate,
              [programId],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, Map<String, dynamic>?>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>?>(
              this,
              Invocation.method(
                #checkProgramDuplicate,
                [programId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> restartProgram(String? programId) =>
      (super.noSuchMethod(
        Invocation.method(
          #restartProgram,
          [programId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #restartProgram,
            [programId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> continueProgram(
          String? programId) =>
      (super.noSuchMethod(
        Invocation.method(
          #continueProgram,
          [programId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #continueProgram,
            [programId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
