// Mocks generated by Mockito 5.4.5 from annotations
// in jfit/test/features/programs/presentation/bloc/programs_bloc_error_handling_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:jfit/core/error/failures.dart' as _i7;
import 'package:jfit/features/programs/data/datasources/program_remote_datasource.dart'
    as _i5;
import 'package:jfit/features/programs/data/models/exercise_model.dart' as _i4;
import 'package:jfit/features/programs/data/models/user_program_day_model.dart'
    as _i9;
import 'package:jfit/features/programs/data/models/workout_log_model.dart'
    as _i11;
import 'package:jfit/features/programs/data/models/workout_program_model.dart'
    as _i2;
import 'package:jfit/features/programs/data/models/workout_session_model.dart'
    as _i10;
import 'package:jfit/features/workout_program/data/models/duplicate_check_result_model.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWorkoutProgramModel_0 extends _i1.SmartFake
    implements _i2.WorkoutProgramModel {
  _FakeWorkoutProgramModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExerciseModel_2 extends _i1.SmartFake implements _i4.ExerciseModel {
  _FakeExerciseModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProgramRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgramRemoteDataSource extends _i1.Mock
    implements _i5.ProgramRemoteDataSource {
  MockProgramRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.WorkoutProgramModel>> getPopularPrograms() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularPrograms,
          [],
        ),
        returnValue: _i6.Future<List<_i2.WorkoutProgramModel>>.value(
            <_i2.WorkoutProgramModel>[]),
      ) as _i6.Future<List<_i2.WorkoutProgramModel>>);

  @override
  _i6.Future<List<_i2.WorkoutProgramModel>> getPrograms({
    String? searchQuery,
    String? difficultyLevel,
    String? programType,
    int? workoutsPerWeek,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrograms,
          [],
          {
            #searchQuery: searchQuery,
            #difficultyLevel: difficultyLevel,
            #programType: programType,
            #workoutsPerWeek: workoutsPerWeek,
            #tags: tags,
          },
        ),
        returnValue: _i6.Future<List<_i2.WorkoutProgramModel>>.value(
            <_i2.WorkoutProgramModel>[]),
      ) as _i6.Future<List<_i2.WorkoutProgramModel>>);

  @override
  _i6.Future<_i2.WorkoutProgramModel> getProgramById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProgramById,
          [id],
        ),
        returnValue: _i6.Future<_i2.WorkoutProgramModel>.value(
            _FakeWorkoutProgramModel_0(
          this,
          Invocation.method(
            #getProgramById,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.WorkoutProgramModel>);

  @override
  _i6.Future<void> addProgramToUser(
    String? programId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProgramToUser,
          [
            programId,
            userId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i8.DuplicateCheckResult>> saveAsMyRoutine(
    String? templateProgramId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAsMyRoutine,
          [
            templateProgramId,
            userId,
          ],
        ),
        returnValue:
            _i6.Future<_i3.Either<_i7.Failure, _i8.DuplicateCheckResult>>.value(
                _FakeEither_1<_i7.Failure, _i8.DuplicateCheckResult>(
          this,
          Invocation.method(
            #saveAsMyRoutine,
            [
              templateProgramId,
              userId,
            ],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, _i8.DuplicateCheckResult>>);

  @override
  _i6.Future<List<_i2.WorkoutProgramModel>> getUserPrograms(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPrograms,
          [userId],
        ),
        returnValue: _i6.Future<List<_i2.WorkoutProgramModel>>.value(
            <_i2.WorkoutProgramModel>[]),
      ) as _i6.Future<List<_i2.WorkoutProgramModel>>);

  @override
  _i6.Future<List<_i2.WorkoutProgramModel>> searchPrograms(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPrograms,
          [query],
        ),
        returnValue: _i6.Future<List<_i2.WorkoutProgramModel>>.value(
            <_i2.WorkoutProgramModel>[]),
      ) as _i6.Future<List<_i2.WorkoutProgramModel>>);

  @override
  _i6.Future<List<_i9.UserProgramDayModel>> getUserProgramDays(
          String? userProgramId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProgramDays,
          [userProgramId],
        ),
        returnValue: _i6.Future<List<_i9.UserProgramDayModel>>.value(
            <_i9.UserProgramDayModel>[]),
      ) as _i6.Future<List<_i9.UserProgramDayModel>>);

  @override
  _i6.Future<List<_i10.WorkoutSessionModel>> getWorkoutSessionsByUserProgram(
          String? userProgramId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutSessionsByUserProgram,
          [userProgramId],
        ),
        returnValue: _i6.Future<List<_i10.WorkoutSessionModel>>.value(
            <_i10.WorkoutSessionModel>[]),
      ) as _i6.Future<List<_i10.WorkoutSessionModel>>);

  @override
  _i6.Future<List<_i11.WorkoutLogModel>> getWorkoutLogsBySession(
          String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutLogsBySession,
          [sessionId],
        ),
        returnValue: _i6.Future<List<_i11.WorkoutLogModel>>.value(
            <_i11.WorkoutLogModel>[]),
      ) as _i6.Future<List<_i11.WorkoutLogModel>>);

  @override
  _i6.Future<_i4.ExerciseModel> getExerciseById(String? exerciseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExerciseById,
          [exerciseId],
        ),
        returnValue: _i6.Future<_i4.ExerciseModel>.value(_FakeExerciseModel_2(
          this,
          Invocation.method(
            #getExerciseById,
            [exerciseId],
          ),
        )),
      ) as _i6.Future<_i4.ExerciseModel>);

  @override
  _i6.Future<Map<String, dynamic>?> checkProgramDuplicate(
    String? programId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkProgramDuplicate,
          [
            programId,
            userId,
          ],
        ),
        returnValue: _i6.Future<Map<String, dynamic>?>.value(),
      ) as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<void> restartProgram(
    String? programId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #restartProgram,
          [
            programId,
            userId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> continueProgram(
    String? programId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #continueProgram,
          [
            programId,
            userId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> cleanupDuplicatePrograms(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cleanupDuplicatePrograms,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
