// Mocks generated by Mockito 5.4.4 from annotations
// in jfit/test/features/programs/presentation/bloc/programs_bloc_error_handling_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:jfit/core/error/failures.dart' as _i5;
import 'package:jfit/features/programs/data/datasources/program_remote_datasource.dart'
    as _i3;
import 'package:jfit/features/workout_program/data/models/duplicate_check_result_model.dart'
    as _i6;
import 'package:jfit/core/error/workout_program_failures.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProgramRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgramRemoteDataSource extends _i1.Mock
    implements _i3.ProgramRemoteDataSource {
  MockProgramRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.DuplicateCheckResult>>
      saveAsMyRoutine(
    String? templateProgramId,
    String? userId,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #saveAsMyRoutine,
              [
                templateProgramId,
                userId,
              ],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.DuplicateCheckResult>>.value(
                    _FakeEither_0<_i5.Failure, _i6.DuplicateCheckResult>(
              this,
              Invocation.method(
                #saveAsMyRoutine,
                [
                  templateProgramId,
                  userId,
                ],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.DuplicateCheckResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.DuplicateCheckResult>>
      saveAsMyRoutineWithOption(
    String? templateProgramId,
    String? userId,
    _i7.ResolutionOption? option, {
    String? existingProgramId,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #saveAsMyRoutineWithOption,
              [
                templateProgramId,
                userId,
                option,
              ],
              {#existingProgramId: existingProgramId},
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.DuplicateCheckResult>>.value(
                    _FakeEither_0<_i5.Failure, _i6.DuplicateCheckResult>(
              this,
              Invocation.method(
                #saveAsMyRoutineWithOption,
                [
                  templateProgramId,
                  userId,
                  option,
                ],
                {#existingProgramId: existingProgramId},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.DuplicateCheckResult>>);
}