// Mocks generated by Mockito 5.4.5 from annotations
// in jfit/test/features/group_workout_community/data/services/content_moderation_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:jfit/core/services/supabase_service.dart' as _i2;
import 'package:jfit/features/analytics/domain/entities/body_data.dart' as _i8;
import 'package:jfit/features/analytics/domain/entities/diet_score_data.dart'
    as _i4;
import 'package:jfit/features/analytics/domain/entities/nutrition_data.dart'
    as _i5;
import 'package:jfit/features/analytics/domain/entities/workout_composition_data.dart'
    as _i7;
import 'package:jfit/features/analytics/domain/entities/workout_time_data.dart'
    as _i6;
import 'package:jfit/features/records/data/models/diet_entry.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SupabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseService extends _i1.Mock implements _i2.SupabaseService {
  MockSupabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.DietScoreData>> getDietScoreData(String? period) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDietScoreData,
          [period],
        ),
        returnValue:
            _i3.Future<List<_i4.DietScoreData>>.value(<_i4.DietScoreData>[]),
      ) as _i3.Future<List<_i4.DietScoreData>>);

  @override
  _i3.Future<List<_i5.NutritionData>> getNutritionData(String? period) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNutritionData,
          [period],
        ),
        returnValue:
            _i3.Future<List<_i5.NutritionData>>.value(<_i5.NutritionData>[]),
      ) as _i3.Future<List<_i5.NutritionData>>);

  @override
  _i3.Future<List<_i6.WorkoutTimeData>> getWorkoutTimeData(String? period) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutTimeData,
          [period],
        ),
        returnValue: _i3.Future<List<_i6.WorkoutTimeData>>.value(
            <_i6.WorkoutTimeData>[]),
      ) as _i3.Future<List<_i6.WorkoutTimeData>>);

  @override
  _i3.Future<List<_i7.WorkoutCompositionData>> getWorkoutCompositionData(
          String? period) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutCompositionData,
          [period],
        ),
        returnValue: _i3.Future<List<_i7.WorkoutCompositionData>>.value(
            <_i7.WorkoutCompositionData>[]),
      ) as _i3.Future<List<_i7.WorkoutCompositionData>>);

  @override
  _i3.Future<List<_i8.BodyData>> getBodyData(String? period) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBodyData,
          [period],
        ),
        returnValue: _i3.Future<List<_i8.BodyData>>.value(<_i8.BodyData>[]),
      ) as _i3.Future<List<_i8.BodyData>>);

  @override
  _i3.Future<void> saveDietEntry(_i9.DietEntry? entry) => (super.noSuchMethod(
        Invocation.method(
          #saveDietEntry,
          [entry],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> searchFoodItems(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFoodItems,
          [query],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<String> saveMealEntry({
    required String? foodName,
    required String? mealType,
    required double? quantityG,
    required DateTime? entryDate,
    required double? calories,
    required double? protein,
    required double? carbohydrates,
    required double? fat,
    String? foodItemId,
    String? notes,
    List<String>? mealTypes,
    String? satisfaction,
    int? score,
    List<String>? accompaniments,
    String? imagePath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMealEntry,
          [],
          {
            #foodName: foodName,
            #mealType: mealType,
            #quantityG: quantityG,
            #entryDate: entryDate,
            #calories: calories,
            #protein: protein,
            #carbohydrates: carbohydrates,
            #fat: fat,
            #foodItemId: foodItemId,
            #notes: notes,
            #mealTypes: mealTypes,
            #satisfaction: satisfaction,
            #score: score,
            #accompaniments: accompaniments,
            #imagePath: imagePath,
          },
        ),
        returnValue: _i3.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #saveMealEntry,
            [],
            {
              #foodName: foodName,
              #mealType: mealType,
              #quantityG: quantityG,
              #entryDate: entryDate,
              #calories: calories,
              #protein: protein,
              #carbohydrates: carbohydrates,
              #fat: fat,
              #foodItemId: foodItemId,
              #notes: notes,
              #mealTypes: mealTypes,
              #satisfaction: satisfaction,
              #score: score,
              #accompaniments: accompaniments,
              #imagePath: imagePath,
            },
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> saveMealEntryFromFoodItem({
    required String? foodItemId,
    required String? foodName,
    required String? mealType,
    required double? quantityG,
    required DateTime? entryDate,
    required double? calories,
    required double? protein,
    required double? carbohydrates,
    required double? fat,
    String? notes,
    List<String>? mealTypes,
    String? satisfaction,
    int? score,
    List<String>? accompaniments,
    String? imagePath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMealEntryFromFoodItem,
          [],
          {
            #foodItemId: foodItemId,
            #foodName: foodName,
            #mealType: mealType,
            #quantityG: quantityG,
            #entryDate: entryDate,
            #calories: calories,
            #protein: protein,
            #carbohydrates: carbohydrates,
            #fat: fat,
            #notes: notes,
            #mealTypes: mealTypes,
            #satisfaction: satisfaction,
            #score: score,
            #accompaniments: accompaniments,
            #imagePath: imagePath,
          },
        ),
        returnValue: _i3.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #saveMealEntryFromFoodItem,
            [],
            {
              #foodItemId: foodItemId,
              #foodName: foodName,
              #mealType: mealType,
              #quantityG: quantityG,
              #entryDate: entryDate,
              #calories: calories,
              #protein: protein,
              #carbohydrates: carbohydrates,
              #fat: fat,
              #notes: notes,
              #mealTypes: mealTypes,
              #satisfaction: satisfaction,
              #score: score,
              #accompaniments: accompaniments,
              #imagePath: imagePath,
            },
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> saveMealEntryManual({
    required String? foodName,
    required String? mealType,
    required double? quantityG,
    required DateTime? entryDate,
    required double? calories,
    required double? protein,
    required double? carbohydrates,
    required double? fat,
    String? notes,
    List<String>? mealTypes,
    String? satisfaction,
    int? score,
    List<String>? accompaniments,
    String? imagePath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMealEntryManual,
          [],
          {
            #foodName: foodName,
            #mealType: mealType,
            #quantityG: quantityG,
            #entryDate: entryDate,
            #calories: calories,
            #protein: protein,
            #carbohydrates: carbohydrates,
            #fat: fat,
            #notes: notes,
            #mealTypes: mealTypes,
            #satisfaction: satisfaction,
            #score: score,
            #accompaniments: accompaniments,
            #imagePath: imagePath,
          },
        ),
        returnValue: _i3.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #saveMealEntryManual,
            [],
            {
              #foodName: foodName,
              #mealType: mealType,
              #quantityG: quantityG,
              #entryDate: entryDate,
              #calories: calories,
              #protein: protein,
              #carbohydrates: carbohydrates,
              #fat: fat,
              #notes: notes,
              #mealTypes: mealTypes,
              #satisfaction: satisfaction,
              #score: score,
              #accompaniments: accompaniments,
              #imagePath: imagePath,
            },
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getMealEntriesForDate(
          DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMealEntriesForDate,
          [date],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getMealEntriesForDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMealEntriesForDateRange,
          [
            startDate,
            endDate,
          ],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> updateMealEntry({
    required String? entryId,
    String? foodName,
    String? mealType,
    double? quantityG,
    double? calories,
    double? protein,
    double? carbohydrates,
    double? fat,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMealEntry,
          [],
          {
            #entryId: entryId,
            #foodName: foodName,
            #mealType: mealType,
            #quantityG: quantityG,
            #calories: calories,
            #protein: protein,
            #carbohydrates: carbohydrates,
            #fat: fat,
            #notes: notes,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMealEntry(String? entryId) => (super.noSuchMethod(
        Invocation.method(
          #deleteMealEntry,
          [entryId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveBodyMeasurement({
    required DateTime? measuredDate,
    double? weight,
    double? muscleMass,
    double? bodyFatPercentage,
    int? conditionRating,
    DateTime? sleepTime,
    DateTime? wakeTime,
    int? bowelCount,
    bool? menstruation,
    String? memo,
    String? photoUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBodyMeasurement,
          [],
          {
            #measuredDate: measuredDate,
            #weight: weight,
            #muscleMass: muscleMass,
            #bodyFatPercentage: bodyFatPercentage,
            #conditionRating: conditionRating,
            #sleepTime: sleepTime,
            #wakeTime: wakeTime,
            #bowelCount: bowelCount,
            #menstruation: menstruation,
            #memo: memo,
            #photoUrl: photoUrl,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> getBodyMeasurementForDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBodyMeasurementForDate,
          [date],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);
}
