// Mocks generated by Mockito 5.4.5 from annotations
// in jfit/test/features/workout_program/utils/workout_program_repository_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:jfit/core/error/failures.dart' as _i6;
import 'package:jfit/features/programs/data/models/user_program_day_model.dart'
    as _i8;
import 'package:jfit/features/workout_program/data/models/current_workout_info_model.dart'
    as _i9;
import 'package:jfit/features/workout_program/data/models/user_program_model.dart'
    as _i7;
import 'package:jfit/features/workout_program/data/repositories/workout_program_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:supabase/supabase.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFunctionsClient_1 extends _i1.SmartFake
    implements _i3.FunctionsClient {
  _FakeFunctionsClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseStorageClient_2 extends _i1.SmartFake
    implements _i3.SupabaseStorageClient {
  _FakeSupabaseStorageClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeClient_3 extends _i1.SmartFake
    implements _i3.RealtimeClient {
  _FakeRealtimeClient_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostgrestClient_4 extends _i1.SmartFake
    implements _i3.PostgrestClient {
  _FakePostgrestClient_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoTrueClient_5 extends _i1.SmartFake implements _i3.GoTrueClient {
  _FakeGoTrueClient_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseQueryBuilder_6 extends _i1.SmartFake
    implements _i3.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseQuerySchema_7 extends _i1.SmartFake
    implements _i3.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostgrestFilterBuilder_8<T1> extends _i1.SmartFake
    implements _i3.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeChannel_9 extends _i1.SmartFake
    implements _i3.RealtimeChannel {
  _FakeRealtimeChannel_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WorkoutProgramRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutProgramRepository extends _i1.Mock
    implements _i4.WorkoutProgramRepository {
  MockWorkoutProgramRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.UserProgramModel>>>
      getUserPrograms(String? userId) => (super.noSuchMethod(
            Invocation.method(
              #getUserPrograms,
              [userId],
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.Failure, List<_i7.UserProgramModel>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.UserProgramModel>>(
              this,
              Invocation.method(
                #getUserPrograms,
                [userId],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.UserProgramModel>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.UserProgramModel?>>
      getUserProgramDetails(String? userProgramId) => (super.noSuchMethod(
            Invocation.method(
              #getUserProgramDetails,
              [userProgramId],
            ),
            returnValue: _i5
                .Future<_i2.Either<_i6.Failure, _i7.UserProgramModel?>>.value(
                _FakeEither_0<_i6.Failure, _i7.UserProgramModel?>(
              this,
              Invocation.method(
                #getUserProgramDetails,
                [userProgramId],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, _i7.UserProgramModel?>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i8.UserProgramDayModel>>>
      getUserProgramDays(String? userProgramId) => (super.noSuchMethod(
            Invocation.method(
              #getUserProgramDays,
              [userProgramId],
            ),
            returnValue: _i5.Future<
                    _i2
                    .Either<_i6.Failure, List<_i8.UserProgramDayModel>>>.value(
                _FakeEither_0<_i6.Failure, List<_i8.UserProgramDayModel>>(
              this,
              Invocation.method(
                #getUserProgramDays,
                [userProgramId],
              ),
            )),
          ) as _i5
              .Future<_i2.Either<_i6.Failure, List<_i8.UserProgramDayModel>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> updateUserProgramProgress(
    String? userProgramId,
    int? currentWeek,
    int? currentDay,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProgramProgress,
          [
            userProgramId,
            currentWeek,
            currentDay,
          ],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #updateUserProgramProgress,
            [
              userProgramId,
              currentWeek,
              currentDay,
            ],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> completeUserProgramDay(
    String? userProgramId,
    int? week,
    int? day, {
    String? note,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeUserProgramDay,
          [
            userProgramId,
            week,
            day,
          ],
          {#note: note},
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #completeUserProgramDay,
            [
              userProgramId,
              week,
              day,
            ],
            {#note: note},
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> deleteUserProgram(
          String? userProgramId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserProgram,
          [userProgramId],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #deleteUserProgram,
            [userProgramId],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i9.CurrentWorkoutInfoModel>>
      getCurrentWorkoutInfo(String? userId) => (super.noSuchMethod(
            Invocation.method(
              #getCurrentWorkoutInfo,
              [userId],
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.Failure, _i9.CurrentWorkoutInfoModel>>.value(
                _FakeEither_0<_i6.Failure, _i9.CurrentWorkoutInfoModel>(
              this,
              Invocation.method(
                #getCurrentWorkoutInfo,
                [userId],
              ),
            )),
          ) as _i5
              .Future<_i2.Either<_i6.Failure, _i9.CurrentWorkoutInfoModel>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.UserProgramModel?>>
      getLatestActiveUserProgram(String? userId) => (super.noSuchMethod(
            Invocation.method(
              #getLatestActiveUserProgram,
              [userId],
            ),
            returnValue: _i5
                .Future<_i2.Either<_i6.Failure, _i7.UserProgramModel?>>.value(
                _FakeEither_0<_i6.Failure, _i7.UserProgramModel?>(
              this,
              Invocation.method(
                #getLatestActiveUserProgram,
                [userId],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, _i7.UserProgramModel?>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, T>> safeCall<T>(
          _i5.Future<T> Function()? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #safeCall,
          [operation],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, T>>.value(
            _FakeEither_0<_i6.Failure, T>(
          this,
          Invocation.method(
            #safeCall,
            [operation],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, T>>);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i3.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FunctionsClient get functions => (super.noSuchMethod(
        Invocation.getter(#functions),
        returnValue: _FakeFunctionsClient_1(
          this,
          Invocation.getter(#functions),
        ),
      ) as _i3.FunctionsClient);

  @override
  set functions(_i3.FunctionsClient? _functions) => super.noSuchMethod(
        Invocation.setter(
          #functions,
          _functions,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.SupabaseStorageClient get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeSupabaseStorageClient_2(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i3.SupabaseStorageClient);

  @override
  set storage(_i3.SupabaseStorageClient? _storage) => super.noSuchMethod(
        Invocation.setter(
          #storage,
          _storage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.RealtimeClient get realtime => (super.noSuchMethod(
        Invocation.getter(#realtime),
        returnValue: _FakeRealtimeClient_3(
          this,
          Invocation.getter(#realtime),
        ),
      ) as _i3.RealtimeClient);

  @override
  set realtime(_i3.RealtimeClient? _realtime) => super.noSuchMethod(
        Invocation.setter(
          #realtime,
          _realtime,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.PostgrestClient get rest => (super.noSuchMethod(
        Invocation.getter(#rest),
        returnValue: _FakePostgrestClient_4(
          this,
          Invocation.getter(#rest),
        ),
      ) as _i3.PostgrestClient);

  @override
  set rest(_i3.PostgrestClient? _rest) => super.noSuchMethod(
        Invocation.setter(
          #rest,
          _rest,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
        Invocation.setter(
          #headers,
          headers,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.GoTrueClient get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeGoTrueClient_5(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i3.GoTrueClient);

  @override
  _i3.SupabaseQueryBuilder from(String? table) => (super.noSuchMethod(
        Invocation.method(
          #from,
          [table],
        ),
        returnValue: _FakeSupabaseQueryBuilder_6(
          this,
          Invocation.method(
            #from,
            [table],
          ),
        ),
      ) as _i3.SupabaseQueryBuilder);

  @override
  _i3.SupabaseQuerySchema schema(String? schema) => (super.noSuchMethod(
        Invocation.method(
          #schema,
          [schema],
        ),
        returnValue: _FakeSupabaseQuerySchema_7(
          this,
          Invocation.method(
            #schema,
            [schema],
          ),
        ),
      ) as _i3.SupabaseQuerySchema);

  @override
  _i3.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rpc,
          [fn],
          {
            #params: params,
            #get: get,
          },
        ),
        returnValue: _FakePostgrestFilterBuilder_8<T>(
          this,
          Invocation.method(
            #rpc,
            [fn],
            {
              #params: params,
              #get: get,
            },
          ),
        ),
      ) as _i3.PostgrestFilterBuilder<T>);

  @override
  _i3.RealtimeChannel channel(
    String? name, {
    _i3.RealtimeChannelConfig? opts = const _i3.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #channel,
          [name],
          {#opts: opts},
        ),
        returnValue: _FakeRealtimeChannel_9(
          this,
          Invocation.method(
            #channel,
            [name],
            {#opts: opts},
          ),
        ),
      ) as _i3.RealtimeChannel);

  @override
  List<_i3.RealtimeChannel> getChannels() => (super.noSuchMethod(
        Invocation.method(
          #getChannels,
          [],
        ),
        returnValue: <_i3.RealtimeChannel>[],
      ) as List<_i3.RealtimeChannel>);

  @override
  _i5.Future<String> removeChannel(_i3.RealtimeChannel? channel) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeChannel,
          [channel],
        ),
        returnValue: _i5.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #removeChannel,
            [channel],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<String>> removeAllChannels() => (super.noSuchMethod(
        Invocation.method(
          #removeAllChannels,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
