// Mocks generated by Mockito 5.4.5 from annotations
// in jfit/test/integration/final_integration_e2e_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:jfit/core/error/failures.dart' as _i5;
import 'package:jfit/features/group_workout_community/domain/entities/community_post.dart'
    as _i24;
import 'package:jfit/features/group_workout_community/domain/entities/group_activity.dart'
    as _i21;
import 'package:jfit/features/group_workout_community/domain/entities/group_member.dart'
    as _i18;
import 'package:jfit/features/group_workout_community/domain/entities/group_search_criteria.dart'
    as _i19;
import 'package:jfit/features/group_workout_community/domain/entities/post_category.dart'
    as _i25;
import 'package:jfit/features/group_workout_community/domain/entities/post_search_criteria.dart'
    as _i26;
import 'package:jfit/features/group_workout_community/domain/entities/shared_routine.dart'
    as _i22;
import 'package:jfit/features/group_workout_community/domain/entities/workout_group.dart'
    as _i17;
import 'package:jfit/features/group_workout_community/domain/repositories/community_repository.dart'
    as _i23;
import 'package:jfit/features/group_workout_community/domain/repositories/group_activity_repository.dart'
    as _i20;
import 'package:jfit/features/group_workout_community/domain/repositories/group_repository.dart'
    as _i16;
import 'package:jfit/features/programs/data/models/exercise_model.dart' as _i15;
import 'package:jfit/features/programs/data/models/user_program_day_model.dart'
    as _i7;
import 'package:jfit/features/programs/data/models/workout_log_model.dart'
    as _i14;
import 'package:jfit/features/programs/data/models/workout_session_model.dart'
    as _i10;
import 'package:jfit/features/programs/domain/entities/workout_program.dart'
    as _i12;
import 'package:jfit/features/programs/domain/repositories/program_repository.dart'
    as _i11;
import 'package:jfit/features/workout_program/data/models/current_workout_info_model.dart'
    as _i8;
import 'package:jfit/features/workout_program/data/models/duplicate_check_result_model.dart'
    as _i13;
import 'package:jfit/features/workout_program/data/models/user_program_model.dart'
    as _i6;
import 'package:jfit/features/workout_program/data/repositories/workout_program_repository.dart'
    as _i3;
import 'package:jfit/features/workout_session/data/repositories/workout_session_repository.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WorkoutProgramRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutProgramRepository extends _i1.Mock
    implements _i3.WorkoutProgramRepository {
  MockWorkoutProgramRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.UserProgramModel>>>
      getUserPrograms(String? userId) => (super.noSuchMethod(
            Invocation.method(
              #getUserPrograms,
              [userId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.UserProgramModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.UserProgramModel>>(
              this,
              Invocation.method(
                #getUserPrograms,
                [userId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.UserProgramModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserProgramModel?>>
      getUserProgramDetails(String? userProgramId) => (super.noSuchMethod(
            Invocation.method(
              #getUserProgramDetails,
              [userProgramId],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i6.UserProgramModel?>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserProgramModel?>(
              this,
              Invocation.method(
                #getUserProgramDetails,
                [userProgramId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserProgramModel?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserProgramDayModel>>>
      getUserProgramDays(String? userProgramId) => (super.noSuchMethod(
            Invocation.method(
              #getUserProgramDays,
              [userProgramId],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i7.UserProgramDayModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.UserProgramDayModel>>(
              this,
              Invocation.method(
                #getUserProgramDays,
                [userProgramId],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i7.UserProgramDayModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateUserProgramProgress(
    String? userProgramId,
    int? currentWeek,
    int? currentDay,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProgramProgress,
          [
            userProgramId,
            currentWeek,
            currentDay,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateUserProgramProgress,
            [
              userProgramId,
              currentWeek,
              currentDay,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> completeUserProgramDay(
    String? userProgramId,
    int? week,
    int? day, {
    String? note,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeUserProgramDay,
          [
            userProgramId,
            week,
            day,
          ],
          {#note: note},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #completeUserProgramDay,
            [
              userProgramId,
              week,
              day,
            ],
            {#note: note},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteUserProgram(
          String? userProgramId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserProgram,
          [userProgramId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteUserProgram,
            [userProgramId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.CurrentWorkoutInfoModel>>
      getCurrentWorkoutInfo(String? userId) => (super.noSuchMethod(
            Invocation.method(
              #getCurrentWorkoutInfo,
              [userId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i8.CurrentWorkoutInfoModel>>.value(
                _FakeEither_0<_i5.Failure, _i8.CurrentWorkoutInfoModel>(
              this,
              Invocation.method(
                #getCurrentWorkoutInfo,
                [userId],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, _i8.CurrentWorkoutInfoModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserProgramModel?>>
      getLatestActiveUserProgram(String? userId) => (super.noSuchMethod(
            Invocation.method(
              #getLatestActiveUserProgram,
              [userId],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i6.UserProgramModel?>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserProgramModel?>(
              this,
              Invocation.method(
                #getLatestActiveUserProgram,
                [userId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserProgramModel?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, T>> safeCall<T>(
          _i4.Future<T> Function()? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #safeCall,
          [operation],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, T>>.value(
            _FakeEither_0<_i5.Failure, T>(
          this,
          Invocation.method(
            #safeCall,
            [operation],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, T>>);
}

/// A class which mocks [WorkoutSessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutSessionRepository extends _i1.Mock
    implements _i9.WorkoutSessionRepository {
  MockWorkoutSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> createWorkoutSession({
    required String? userProgramId,
    required Map<String, dynamic>? exercisesJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWorkoutSession,
          [],
          {
            #userProgramId: userProgramId,
            #exercisesJson: exercisesJson,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #createWorkoutSession,
            [],
            {
              #userProgramId: userProgramId,
              #exercisesJson: exercisesJson,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i10.WorkoutSessionModel?>>
      getWorkoutSession(String? sessionId) => (super.noSuchMethod(
            Invocation.method(
              #getWorkoutSession,
              [sessionId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i10.WorkoutSessionModel?>>.value(
                _FakeEither_0<_i5.Failure, _i10.WorkoutSessionModel?>(
              this,
              Invocation.method(
                #getWorkoutSession,
                [sessionId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i10.WorkoutSessionModel?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i10.WorkoutSessionModel>>>
      getWorkoutSessions(String? userId) => (super.noSuchMethod(
            Invocation.method(
              #getWorkoutSessions,
              [userId],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i10.WorkoutSessionModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i10.WorkoutSessionModel>>(
              this,
              Invocation.method(
                #getWorkoutSessions,
                [userId],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i10.WorkoutSessionModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i10.WorkoutSessionModel>>>
      getActiveWorkoutSessions(String? userId) => (super.noSuchMethod(
            Invocation.method(
              #getActiveWorkoutSessions,
              [userId],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i10.WorkoutSessionModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i10.WorkoutSessionModel>>(
              this,
              Invocation.method(
                #getActiveWorkoutSessions,
                [userId],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i10.WorkoutSessionModel>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i10.WorkoutSessionModel>> updateWorkoutSession({
    required String? sessionId,
    required Map<String, dynamic>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkoutSession,
          [],
          {
            #sessionId: sessionId,
            #updates: updates,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i10.WorkoutSessionModel>>.value(
                _FakeEither_0<_i5.Failure, _i10.WorkoutSessionModel>(
          this,
          Invocation.method(
            #updateWorkoutSession,
            [],
            {
              #sessionId: sessionId,
              #updates: updates,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i10.WorkoutSessionModel>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i10.WorkoutSessionModel>> completeWorkoutSession(
          String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeWorkoutSession,
          [sessionId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i10.WorkoutSessionModel>>.value(
                _FakeEither_0<_i5.Failure, _i10.WorkoutSessionModel>(
          this,
          Invocation.method(
            #completeWorkoutSession,
            [sessionId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i10.WorkoutSessionModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> logWorkoutSet({
    required String? sessionId,
    required String? exerciseId,
    required int? setNumber,
    required int? reps,
    required double? weight,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logWorkoutSet,
          [],
          {
            #sessionId: sessionId,
            #exerciseId: exerciseId,
            #setNumber: setNumber,
            #reps: reps,
            #weight: weight,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #logWorkoutSet,
            [],
            {
              #sessionId: sessionId,
              #exerciseId: exerciseId,
              #setNumber: setNumber,
              #reps: reps,
              #weight: weight,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>?>>
      getLastWorkoutLogByExercise({
    required String? exerciseId,
    required String? userId,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getLastWorkoutLogByExercise,
              [],
              {
                #exerciseId: exerciseId,
                #userId: userId,
              },
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, Map<String, dynamic>?>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>?>(
              this,
              Invocation.method(
                #getLastWorkoutLogByExercise,
                [],
                {
                  #exerciseId: exerciseId,
                  #userId: userId,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> getOrCreateExerciseId(
          String? exerciseName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrCreateExerciseId,
          [exerciseName],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #getOrCreateExerciseId,
            [exerciseName],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, T>> safeCall<T>(
          _i4.Future<T> Function()? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #safeCall,
          [operation],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, T>>.value(
            _FakeEither_0<_i5.Failure, T>(
          this,
          Invocation.method(
            #safeCall,
            [operation],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, T>>);
}

/// A class which mocks [ProgramRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgramRepository extends _i1.Mock implements _i11.ProgramRepository {
  MockProgramRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i12.WorkoutProgram>>>
      getPopularPrograms() => (super.noSuchMethod(
            Invocation.method(
              #getPopularPrograms,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i12.WorkoutProgram>>>.value(
                _FakeEither_0<_i5.Failure, List<_i12.WorkoutProgram>>(
              this,
              Invocation.method(
                #getPopularPrograms,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i12.WorkoutProgram>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i12.WorkoutProgram>>> getPrograms({
    String? searchQuery,
    String? difficultyLevel,
    String? programType,
    int? workoutsPerWeek,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrograms,
          [],
          {
            #searchQuery: searchQuery,
            #difficultyLevel: difficultyLevel,
            #programType: programType,
            #workoutsPerWeek: workoutsPerWeek,
            #tags: tags,
          },
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<_i12.WorkoutProgram>>>.value(
            _FakeEither_0<_i5.Failure, List<_i12.WorkoutProgram>>(
          this,
          Invocation.method(
            #getPrograms,
            [],
            {
              #searchQuery: searchQuery,
              #difficultyLevel: difficultyLevel,
              #programType: programType,
              #workoutsPerWeek: workoutsPerWeek,
              #tags: tags,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i12.WorkoutProgram>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i12.WorkoutProgram>> getProgramById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProgramById,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i12.WorkoutProgram>>.value(
                _FakeEither_0<_i5.Failure, _i12.WorkoutProgram>(
          this,
          Invocation.method(
            #getProgramById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i12.WorkoutProgram>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addProgramToUser(
          String? programId) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProgramToUser,
          [programId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #addProgramToUser,
            [programId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i13.DuplicateCheckResult>>
      saveAsMyRoutine(String? templateProgramId) => (super.noSuchMethod(
            Invocation.method(
              #saveAsMyRoutine,
              [templateProgramId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i13.DuplicateCheckResult>>.value(
                _FakeEither_0<_i5.Failure, _i13.DuplicateCheckResult>(
              this,
              Invocation.method(
                #saveAsMyRoutine,
                [templateProgramId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i13.DuplicateCheckResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i12.WorkoutProgram>>>
      getUserPrograms() => (super.noSuchMethod(
            Invocation.method(
              #getUserPrograms,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i12.WorkoutProgram>>>.value(
                _FakeEither_0<_i5.Failure, List<_i12.WorkoutProgram>>(
              this,
              Invocation.method(
                #getUserPrograms,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i12.WorkoutProgram>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i12.WorkoutProgram>>> searchPrograms(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPrograms,
          [query],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<_i12.WorkoutProgram>>>.value(
            _FakeEither_0<_i5.Failure, List<_i12.WorkoutProgram>>(
          this,
          Invocation.method(
            #searchPrograms,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i12.WorkoutProgram>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserProgramDayModel>>>
      getUserProgramDays(String? userProgramId) => (super.noSuchMethod(
            Invocation.method(
              #getUserProgramDays,
              [userProgramId],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i7.UserProgramDayModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.UserProgramDayModel>>(
              this,
              Invocation.method(
                #getUserProgramDays,
                [userProgramId],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i7.UserProgramDayModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i10.WorkoutSessionModel>>>
      getWorkoutSessionsByUserProgram(String? userProgramId) =>
          (super.noSuchMethod(
            Invocation.method(
              #getWorkoutSessionsByUserProgram,
              [userProgramId],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i10.WorkoutSessionModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i10.WorkoutSessionModel>>(
              this,
              Invocation.method(
                #getWorkoutSessionsByUserProgram,
                [userProgramId],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i10.WorkoutSessionModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i14.WorkoutLogModel>>>
      getWorkoutLogsBySession(String? sessionId) => (super.noSuchMethod(
            Invocation.method(
              #getWorkoutLogsBySession,
              [sessionId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i14.WorkoutLogModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i14.WorkoutLogModel>>(
              this,
              Invocation.method(
                #getWorkoutLogsBySession,
                [sessionId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i14.WorkoutLogModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i15.ExerciseModel>> getExerciseById(
          String? exerciseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExerciseById,
          [exerciseId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i15.ExerciseModel>>.value(
                _FakeEither_0<_i5.Failure, _i15.ExerciseModel>(
          this,
          Invocation.method(
            #getExerciseById,
            [exerciseId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i15.ExerciseModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>?>>
      checkProgramDuplicate(String? programId) => (super.noSuchMethod(
            Invocation.method(
              #checkProgramDuplicate,
              [programId],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, Map<String, dynamic>?>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>?>(
              this,
              Invocation.method(
                #checkProgramDuplicate,
                [programId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> restartProgram(String? programId) =>
      (super.noSuchMethod(
        Invocation.method(
          #restartProgram,
          [programId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #restartProgram,
            [programId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> continueProgram(
          String? programId) =>
      (super.noSuchMethod(
        Invocation.method(
          #continueProgram,
          [programId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #continueProgram,
            [programId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [GroupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupRepository extends _i1.Mock implements _i16.GroupRepository {
  MockGroupRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i17.WorkoutGroup>>> getUserGroups(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserGroups,
          [userId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i17.WorkoutGroup>>>.value(
                _FakeEither_0<_i5.Failure, List<_i17.WorkoutGroup>>(
          this,
          Invocation.method(
            #getUserGroups,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i17.WorkoutGroup>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i17.WorkoutGroup>>> getPublicGroups({
    int? limit = 20,
    int? offset = 0,
    String? searchQuery,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublicGroups,
          [],
          {
            #limit: limit,
            #offset: offset,
            #searchQuery: searchQuery,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i17.WorkoutGroup>>>.value(
                _FakeEither_0<_i5.Failure, List<_i17.WorkoutGroup>>(
          this,
          Invocation.method(
            #getPublicGroups,
            [],
            {
              #limit: limit,
              #offset: offset,
              #searchQuery: searchQuery,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i17.WorkoutGroup>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i17.WorkoutGroup?>> getGroupById(
          String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupById,
          [groupId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i17.WorkoutGroup?>>.value(
                _FakeEither_0<_i5.Failure, _i17.WorkoutGroup?>(
          this,
          Invocation.method(
            #getGroupById,
            [groupId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i17.WorkoutGroup?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i17.WorkoutGroup>> createGroup(
    _i16.CreateGroupRequest? request,
    String? creatorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGroup,
          [
            request,
            creatorId,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i17.WorkoutGroup>>.value(
                _FakeEither_0<_i5.Failure, _i17.WorkoutGroup>(
          this,
          Invocation.method(
            #createGroup,
            [
              request,
              creatorId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i17.WorkoutGroup>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> joinGroup(
          _i16.JoinGroupRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinGroup,
          [request],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #joinGroup,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> leaveGroup(
    String? groupId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #leaveGroup,
          [
            groupId,
            userId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #leaveGroup,
            [
              groupId,
              userId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i18.GroupMember>>> getGroupMembers(
          String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupMembers,
          [groupId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i18.GroupMember>>>.value(
                _FakeEither_0<_i5.Failure, List<_i18.GroupMember>>(
          this,
          Invocation.method(
            #getGroupMembers,
            [groupId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i18.GroupMember>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i17.WorkoutGroup>> updateGroupSettings(
    String? groupId,
    _i16.UpdateGroupRequest? request,
    String? adminId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGroupSettings,
          [
            groupId,
            request,
            adminId,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i17.WorkoutGroup>>.value(
                _FakeEither_0<_i5.Failure, _i17.WorkoutGroup>(
          this,
          Invocation.method(
            #updateGroupSettings,
            [
              groupId,
              request,
              adminId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i17.WorkoutGroup>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeGroupMember(
    String? groupId,
    String? memberUserId,
    String? adminId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeGroupMember,
          [
            groupId,
            memberUserId,
            adminId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #removeGroupMember,
            [
              groupId,
              memberUserId,
              adminId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateMemberRole(
    String? groupId,
    String? memberUserId,
    _i17.GroupRole? newRole,
    String? adminId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemberRole,
          [
            groupId,
            memberUserId,
            newRole,
            adminId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateMemberRole,
            [
              groupId,
              memberUserId,
              newRole,
              adminId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> transferOwnership(
    String? groupId,
    String? newAdminUserId,
    String? currentAdminId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #transferOwnership,
          [
            groupId,
            newAdminUserId,
            currentAdminId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #transferOwnership,
            [
              groupId,
              newAdminUserId,
              currentAdminId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> generateInviteCode(
    String? groupId,
    String? adminId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateInviteCode,
          [
            groupId,
            adminId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #generateInviteCode,
            [
              groupId,
              adminId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> validateInviteCode(
    String? groupId,
    String? inviteCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateInviteCode,
          [
            groupId,
            inviteCode,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #validateInviteCode,
            [
              groupId,
              inviteCode,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i18.GroupMember?>> getGroupMembership(
    String? groupId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupMembership,
          [
            groupId,
            userId,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i18.GroupMember?>>.value(
                _FakeEither_0<_i5.Failure, _i18.GroupMember?>(
          this,
          Invocation.method(
            #getGroupMembership,
            [
              groupId,
              userId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i18.GroupMember?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i17.WorkoutGroup>>> getManagedGroups(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getManagedGroups,
          [userId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i17.WorkoutGroup>>>.value(
                _FakeEither_0<_i5.Failure, List<_i17.WorkoutGroup>>(
          this,
          Invocation.method(
            #getManagedGroups,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i17.WorkoutGroup>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deactivateGroup(
    String? groupId,
    String? adminId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deactivateGroup,
          [
            groupId,
            adminId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deactivateGroup,
            [
              groupId,
              adminId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> getGroupStats(
          String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupStats,
          [groupId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #getGroupStats,
            [groupId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i17.WorkoutGroup>>> searchGroups({
    required _i19.GroupSearchCriteria? criteria,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchGroups,
          [],
          {
            #criteria: criteria,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i17.WorkoutGroup>>>.value(
                _FakeEither_0<_i5.Failure, List<_i17.WorkoutGroup>>(
          this,
          Invocation.method(
            #searchGroups,
            [],
            {
              #criteria: criteria,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i17.WorkoutGroup>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i17.WorkoutGroup>>> getSuggestedGroups(
    String? userId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSuggestedGroups,
          [userId],
          {#limit: limit},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i17.WorkoutGroup>>>.value(
                _FakeEither_0<_i5.Failure, List<_i17.WorkoutGroup>>(
          this,
          Invocation.method(
            #getSuggestedGroups,
            [userId],
            {#limit: limit},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i17.WorkoutGroup>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i17.WorkoutGroup>>>
      getTrendingGroups({int? limit = 10}) => (super.noSuchMethod(
            Invocation.method(
              #getTrendingGroups,
              [],
              {#limit: limit},
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i17.WorkoutGroup>>>.value(
                _FakeEither_0<_i5.Failure, List<_i17.WorkoutGroup>>(
              this,
              Invocation.method(
                #getTrendingGroups,
                [],
                {#limit: limit},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i17.WorkoutGroup>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, T>> safeCall<T>(
          _i4.Future<T> Function()? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #safeCall,
          [operation],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, T>>.value(
            _FakeEither_0<_i5.Failure, T>(
          this,
          Invocation.method(
            #safeCall,
            [operation],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, T>>);
}

/// A class which mocks [GroupActivityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupActivityRepository extends _i1.Mock
    implements _i20.GroupActivityRepository {
  MockGroupActivityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i21.GroupActivity>>> getGroupActivities(
    String? groupId, {
    int? limit = 50,
    int? offset = 0,
    List<_i17.GroupActivityType>? activityTypes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupActivities,
          [groupId],
          {
            #limit: limit,
            #offset: offset,
            #activityTypes: activityTypes,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i21.GroupActivity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i21.GroupActivity>>(
          this,
          Invocation.method(
            #getGroupActivities,
            [groupId],
            {
              #limit: limit,
              #offset: offset,
              #activityTypes: activityTypes,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i21.GroupActivity>>>);

  @override
  _i4.Future<
      _i2
      .Either<_i5.Failure, List<_i21.GroupActivity>>> getUserActivitiesInGroup(
    String? groupId,
    String? userId, {
    int? limit = 20,
    DateTime? since,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserActivitiesInGroup,
          [
            groupId,
            userId,
          ],
          {
            #limit: limit,
            #since: since,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i21.GroupActivity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i21.GroupActivity>>(
          this,
          Invocation.method(
            #getUserActivitiesInGroup,
            [
              groupId,
              userId,
            ],
            {
              #limit: limit,
              #since: since,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i21.GroupActivity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i22.SharedRoutine>> shareRoutine(
          _i20.ShareRoutineRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareRoutine,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i22.SharedRoutine>>.value(
                _FakeEither_0<_i5.Failure, _i22.SharedRoutine>(
          this,
          Invocation.method(
            #shareRoutine,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i22.SharedRoutine>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>> logWorkoutCompletion(
          _i20.WorkoutCompletionRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #logWorkoutCompletion,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>>.value(
                _FakeEither_0<_i5.Failure, _i21.GroupActivity>(
          this,
          Invocation.method(
            #logWorkoutCompletion,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>> sendEncouragement(
          _i20.EncouragementRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEncouragement,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>>.value(
                _FakeEither_0<_i5.Failure, _i21.GroupActivity>(
          this,
          Invocation.method(
            #sendEncouragement,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i22.SharedRoutine>>> getSharedRoutines(
    String? groupId, {
    int? limit = 20,
    int? offset = 0,
    String? orderBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSharedRoutines,
          [groupId],
          {
            #limit: limit,
            #offset: offset,
            #orderBy: orderBy,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i22.SharedRoutine>>>.value(
                _FakeEither_0<_i5.Failure, List<_i22.SharedRoutine>>(
          this,
          Invocation.method(
            #getSharedRoutines,
            [groupId],
            {
              #limit: limit,
              #offset: offset,
              #orderBy: orderBy,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i22.SharedRoutine>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i22.SharedRoutine?>> getSharedRoutineById(
          String? routineId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSharedRoutineById,
          [routineId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i22.SharedRoutine?>>.value(
                _FakeEither_0<_i5.Failure, _i22.SharedRoutine?>(
          this,
          Invocation.method(
            #getSharedRoutineById,
            [routineId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i22.SharedRoutine?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> copySharedRoutine(
          _i20.CopyRoutineRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #copySharedRoutine,
          [request],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #copySharedRoutine,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> toggleRoutineLike(
    String? sharedRoutineId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleRoutineLike,
          [
            sharedRoutineId,
            userId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #toggleRoutineLike,
            [
              sharedRoutineId,
              userId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> hasUserLikedRoutine(
    String? sharedRoutineId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasUserLikedRoutine,
          [
            sharedRoutineId,
            userId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #hasUserLikedRoutine,
            [
              sharedRoutineId,
              userId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i22.SharedRoutine>>> getUserSharedRoutines(
    String? userId, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserSharedRoutines,
          [userId],
          {#limit: limit},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i22.SharedRoutine>>>.value(
                _FakeEither_0<_i5.Failure, List<_i22.SharedRoutine>>(
          this,
          Invocation.method(
            #getUserSharedRoutines,
            [userId],
            {#limit: limit},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i22.SharedRoutine>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteSharedRoutine(
    String? sharedRoutineId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSharedRoutine,
          [
            sharedRoutineId,
            userId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteSharedRoutine,
            [
              sharedRoutineId,
              userId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>> logMemberJoined(
    String? groupId,
    String? userId,
    String? welcomeMessage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logMemberJoined,
          [
            groupId,
            userId,
            welcomeMessage,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>>.value(
                _FakeEither_0<_i5.Failure, _i21.GroupActivity>(
          this,
          Invocation.method(
            #logMemberJoined,
            [
              groupId,
              userId,
              welcomeMessage,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>> logMemberLeft(
    String? groupId,
    String? userId,
    String? farewell,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logMemberLeft,
          [
            groupId,
            userId,
            farewell,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>>.value(
                _FakeEither_0<_i5.Failure, _i21.GroupActivity>(
          this,
          Invocation.method(
            #logMemberLeft,
            [
              groupId,
              userId,
              farewell,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>>
      logAchievementUnlocked(
    String? groupId,
    String? userId,
    String? achievementName,
    String? achievementDescription,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #logAchievementUnlocked,
              [
                groupId,
                userId,
                achievementName,
                achievementDescription,
              ],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>>.value(
                    _FakeEither_0<_i5.Failure, _i21.GroupActivity>(
              this,
              Invocation.method(
                #logAchievementUnlocked,
                [
                  groupId,
                  userId,
                  achievementName,
                  achievementDescription,
                ],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>> logProgramStarted(
    String? groupId,
    String? userId,
    String? programName,
    int? durationWeeks,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logProgramStarted,
          [
            groupId,
            userId,
            programName,
            durationWeeks,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>>.value(
                _FakeEither_0<_i5.Failure, _i21.GroupActivity>(
          this,
          Invocation.method(
            #logProgramStarted,
            [
              groupId,
              userId,
              programName,
              durationWeeks,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>> logMilestoneReached(
    String? groupId,
    String? userId,
    String? milestoneType,
    Map<String, dynamic>? milestoneData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logMilestoneReached,
          [
            groupId,
            userId,
            milestoneType,
            milestoneData,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>>.value(
                _FakeEither_0<_i5.Failure, _i21.GroupActivity>(
          this,
          Invocation.method(
            #logMilestoneReached,
            [
              groupId,
              userId,
              milestoneType,
              milestoneData,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i21.GroupActivity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>
      getGroupActivityStats(
    String? groupId, {
    DateTime? startDate,
    DateTime? endDate,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getGroupActivityStats,
              [groupId],
              {
                #startDate: startDate,
                #endDate: endDate,
              },
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                    _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
              this,
              Invocation.method(
                #getGroupActivityStats,
                [groupId],
                {
                  #startDate: startDate,
                  #endDate: endDate,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>
      getMostActiveMembers(
    String? groupId, {
    int? limit = 10,
    int? days = 30,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getMostActiveMembers,
              [groupId],
              {
                #limit: limit,
                #days: days,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<Map<String, dynamic>>>>.value(
                _FakeEither_0<_i5.Failure, List<Map<String, dynamic>>>(
              this,
              Invocation.method(
                #getMostActiveMembers,
                [groupId],
                {
                  #limit: limit,
                  #days: days,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i21.GroupActivity>>>
      getActivitiesMentioningUser(
    String? userId, {
    int? limit = 20,
    bool? unreadOnly = false,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getActivitiesMentioningUser,
              [userId],
              {
                #limit: limit,
                #unreadOnly: unreadOnly,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i21.GroupActivity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i21.GroupActivity>>(
              this,
              Invocation.method(
                #getActivitiesMentioningUser,
                [userId],
                {
                  #limit: limit,
                  #unreadOnly: unreadOnly,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i21.GroupActivity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> markActivitiesAsRead(
    List<String>? activityIds,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markActivitiesAsRead,
          [
            activityIds,
            userId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #markActivitiesAsRead,
            [
              activityIds,
              userId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, T>> safeCall<T>(
          _i4.Future<T> Function()? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #safeCall,
          [operation],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, T>>.value(
            _FakeEither_0<_i5.Failure, T>(
          this,
          Invocation.method(
            #safeCall,
            [operation],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, T>>);
}

/// A class which mocks [CommunityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommunityRepository extends _i1.Mock
    implements _i23.CommunityRepository {
  MockCommunityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>> getPosts(
          _i23.PostSearchRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPosts,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>.value(
                _FakeEither_0<_i5.Failure, List<_i24.CommunityPost>>(
          this,
          Invocation.method(
            #getPosts,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i24.CommunityPost?>> getPostById(
          String? postId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPostById,
          [postId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i24.CommunityPost?>>.value(
                _FakeEither_0<_i5.Failure, _i24.CommunityPost?>(
          this,
          Invocation.method(
            #getPostById,
            [postId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i24.CommunityPost?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i24.CommunityPost>> createPost(
          _i23.CreatePostRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPost,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i24.CommunityPost>>.value(
                _FakeEither_0<_i5.Failure, _i24.CommunityPost>(
          this,
          Invocation.method(
            #createPost,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i24.CommunityPost>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i24.CommunityPost>> updatePost(
    String? postId,
    _i23.UpdatePostRequest? request,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePost,
          [
            postId,
            request,
            userId,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i24.CommunityPost>>.value(
                _FakeEither_0<_i5.Failure, _i24.CommunityPost>(
          this,
          Invocation.method(
            #updatePost,
            [
              postId,
              request,
              userId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i24.CommunityPost>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deletePost(
    String? postId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePost,
          [
            postId,
            userId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deletePost,
            [
              postId,
              userId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i25.PostCategory>>>
      getCategories() => (super.noSuchMethod(
            Invocation.method(
              #getCategories,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i25.PostCategory>>>.value(
                _FakeEither_0<_i5.Failure, List<_i25.PostCategory>>(
              this,
              Invocation.method(
                #getCategories,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i25.PostCategory>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i25.PostCategory?>> getCategoryById(
          String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoryById,
          [categoryId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i25.PostCategory?>>.value(
                _FakeEither_0<_i5.Failure, _i25.PostCategory?>(
          this,
          Invocation.method(
            #getCategoryById,
            [categoryId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i25.PostCategory?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i25.PostCategory>> createCategory(
          _i23.CreateCategoryRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCategory,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i25.PostCategory>>.value(
                _FakeEither_0<_i5.Failure, _i25.PostCategory>(
          this,
          Invocation.method(
            #createCategory,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i25.PostCategory>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i25.PostCategory>> updateCategory(
    String? categoryId,
    _i23.CreateCategoryRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [
            categoryId,
            request,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i25.PostCategory>>.value(
                _FakeEither_0<_i5.Failure, _i25.PostCategory>(
          this,
          Invocation.method(
            #updateCategory,
            [
              categoryId,
              request,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i25.PostCategory>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteCategory(
          String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [categoryId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteCategory,
            [categoryId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> uploadMedia(
          List<String>? filePaths) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadMedia,
          [filePaths],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
            _FakeEither_0<_i5.Failure, List<String>>(
          this,
          Invocation.method(
            #uploadMedia,
            [filePaths],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteMedia(
          List<String>? mediaUrls) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMedia,
          [mediaUrls],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteMedia,
            [mediaUrls],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i24.CommunityPost>>> getPostsByAuthor(
    String? authorId, {
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPostsByAuthor,
          [authorId],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>.value(
                _FakeEither_0<_i5.Failure, List<_i24.CommunityPost>>(
          this,
          Invocation.method(
            #getPostsByAuthor,
            [authorId],
            {
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i24.CommunityPost>>> getPopularPosts({
    String? categoryId,
    String? groupId,
    int? days = 7,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularPosts,
          [],
          {
            #categoryId: categoryId,
            #groupId: groupId,
            #days: days,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>.value(
                _FakeEither_0<_i5.Failure, List<_i24.CommunityPost>>(
          this,
          Invocation.method(
            #getPopularPosts,
            [],
            {
              #categoryId: categoryId,
              #groupId: groupId,
              #days: days,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i24.CommunityPost>>> getTrendingPosts({
    String? categoryId,
    String? groupId,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrendingPosts,
          [],
          {
            #categoryId: categoryId,
            #groupId: groupId,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>.value(
                _FakeEither_0<_i5.Failure, List<_i24.CommunityPost>>(
          this,
          Invocation.method(
            #getTrendingPosts,
            [],
            {
              #categoryId: categoryId,
              #groupId: groupId,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>> getPinnedPosts({
    String? categoryId,
    String? groupId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPinnedPosts,
          [],
          {
            #categoryId: categoryId,
            #groupId: groupId,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>.value(
                _FakeEither_0<_i5.Failure, List<_i24.CommunityPost>>(
          this,
          Invocation.method(
            #getPinnedPosts,
            [],
            {
              #categoryId: categoryId,
              #groupId: groupId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> togglePostPin(
    String? postId,
    String? adminId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #togglePostPin,
          [
            postId,
            adminId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #togglePostPin,
            [
              postId,
              adminId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>> searchPosts(
    String? query, {
    String? categoryId,
    String? groupId,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPosts,
          [query],
          {
            #categoryId: categoryId,
            #groupId: groupId,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>.value(
                _FakeEither_0<_i5.Failure, List<_i24.CommunityPost>>(
          this,
          Invocation.method(
            #searchPosts,
            [query],
            {
              #categoryId: categoryId,
              #groupId: groupId,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>> getPostsByTags(
    List<String>? tags, {
    String? categoryId,
    String? groupId,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPostsByTags,
          [tags],
          {
            #categoryId: categoryId,
            #groupId: groupId,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>.value(
                _FakeEither_0<_i5.Failure, List<_i24.CommunityPost>>(
          this,
          Invocation.method(
            #getPostsByTags,
            [tags],
            {
              #categoryId: categoryId,
              #groupId: groupId,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> getAllTags({
    String? categoryId,
    String? groupId,
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTags,
          [],
          {
            #categoryId: categoryId,
            #groupId: groupId,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
            _FakeEither_0<_i5.Failure, List<String>>(
          this,
          Invocation.method(
            #getAllTags,
            [],
            {
              #categoryId: categoryId,
              #groupId: groupId,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> getPostStats({
    String? categoryId,
    String? groupId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPostStats,
          [],
          {
            #categoryId: categoryId,
            #groupId: groupId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #getPostStats,
            [],
            {
              #categoryId: categoryId,
              #groupId: groupId,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>
      getCategoryStats() => (super.noSuchMethod(
            Invocation.method(
              #getCategoryStats,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                    _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
              this,
              Invocation.method(
                #getCategoryStats,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> reportPost(
    String? postId,
    String? reporterId,
    String? reason,
    String? description,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportPost,
          [
            postId,
            reporterId,
            reason,
            description,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #reportPost,
            [
              postId,
              reporterId,
              reason,
              description,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>
      getReportedPosts({
    int? limit = 20,
    int? offset = 0,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getReportedPosts,
              [],
              {
                #limit: limit,
                #offset: offset,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<Map<String, dynamic>>>>.value(
                _FakeEither_0<_i5.Failure, List<Map<String, dynamic>>>(
              this,
              Invocation.method(
                #getReportedPosts,
                [],
                {
                  #limit: limit,
                  #offset: offset,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> resolvePostReport(
    String? reportId,
    String? adminId,
    String? resolution,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolvePostReport,
          [
            reportId,
            adminId,
            resolution,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #resolvePostReport,
            [
              reportId,
              adminId,
              resolution,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<
      _i2
      .Either<_i5.Failure, List<_i24.CommunityPost>>> searchPostsWithCriteria({
    required _i26.PostSearchCriteria? criteria,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPostsWithCriteria,
          [],
          {
            #criteria: criteria,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>.value(
                _FakeEither_0<_i5.Failure, List<_i24.CommunityPost>>(
          this,
          Invocation.method(
            #searchPostsWithCriteria,
            [],
            {
              #criteria: criteria,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i24.CommunityPost>>> getSuggestedPosts(
    String? userId, {
    String? groupId,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSuggestedPosts,
          [userId],
          {
            #groupId: groupId,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>.value(
                _FakeEither_0<_i5.Failure, List<_i24.CommunityPost>>(
          this,
          Invocation.method(
            #getSuggestedPosts,
            [userId],
            {
              #groupId: groupId,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>> getRelatedPosts(
    String? postId, {
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRelatedPosts,
          [postId],
          {#limit: limit},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>.value(
                _FakeEither_0<_i5.Failure, List<_i24.CommunityPost>>(
          this,
          Invocation.method(
            #getRelatedPosts,
            [postId],
            {#limit: limit},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i24.CommunityPost>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> searchTags(
    String? query, {
    String? categoryId,
    String? groupId,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTags,
          [query],
          {
            #categoryId: categoryId,
            #groupId: groupId,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
            _FakeEither_0<_i5.Failure, List<String>>(
          this,
          Invocation.method(
            #searchTags,
            [query],
            {
              #categoryId: categoryId,
              #groupId: groupId,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> getSearchSuggestions(
    String? userId, {
    String? partialQuery,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchSuggestions,
          [userId],
          {
            #partialQuery: partialQuery,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
            _FakeEither_0<_i5.Failure, List<String>>(
          this,
          Invocation.method(
            #getSearchSuggestions,
            [userId],
            {
              #partialQuery: partialQuery,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> saveSearchQuery(
    String? userId,
    String? query,
    int? resultCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSearchQuery,
          [
            userId,
            query,
            resultCount,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #saveSearchQuery,
            [
              userId,
              query,
              resultCount,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, T>> safeCall<T>(
          _i4.Future<T> Function()? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #safeCall,
          [operation],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, T>>.value(
            _FakeEither_0<_i5.Failure, T>(
          this,
          Invocation.method(
            #safeCall,
            [operation],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, T>>);
}
