// Mocks generated by Mockito 5.4.6 from annotations
// in jfit/test/integration/user_scenario_e2e_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:bloc/bloc.dart' as _i20;
import 'package:dartz/dartz.dart' as _i2;
import 'package:jfit/core/error/failures.dart' as _i6;
import 'package:jfit/core/models/exercise.dart' as _i17;
import 'package:jfit/features/auth/bloc/auth_bloc.dart' as _i18;
import 'package:jfit/features/auth/bloc/auth_event.dart' as _i19;
import 'package:jfit/features/auth/bloc/auth_state.dart' as _i3;
import 'package:jfit/features/daily_summary/data/repositories/daily_summary_repository.dart'
    as _i14;
import 'package:jfit/features/exercise/data/repositories/exercise_repository.dart'
    as _i16;
import 'package:jfit/features/meal/data/repositories/meal_repository.dart'
    as _i4;
import 'package:jfit/features/programs/data/models/user_program_day_model.dart'
    as _i10;
import 'package:jfit/features/programs/data/models/workout_session_model.dart'
    as _i13;
import 'package:jfit/features/records/data/models/meal_record_model.dart'
    as _i7;
import 'package:jfit/features/records/data/models/user_daily_summary_model.dart'
    as _i15;
import 'package:jfit/features/workout_program/data/models/current_workout_info_model.dart'
    as _i11;
import 'package:jfit/features/workout_program/data/models/user_program_model.dart'
    as _i9;
import 'package:jfit/features/workout_program/data/repositories/workout_program_repository.dart'
    as _i8;
import 'package:jfit/features/workout_session/data/repositories/workout_session_repository.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthState_1 extends _i1.SmartFake implements _i3.AuthState {
  _FakeAuthState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MealRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealRepository extends _i1.Mock implements _i4.MealRepository {
  MockMealRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.MealRecord>>> getMealRecords(
    String? userId, {
    DateTime? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMealRecords, [userId], {#date: date}),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.MealRecord>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.MealRecord>>(
                    this,
                    Invocation.method(#getMealRecords, [userId], {#date: date}),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.MealRecord>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> addMealRecord(
    _i7.MealRecord? record,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addMealRecord, [record]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#addMealRecord, [record]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> updateMealRecord(
    _i7.MealRecord? record,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMealRecord, [record]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#updateMealRecord, [record]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> deleteMealRecord(
    String? recordId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMealRecord, [recordId]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#deleteMealRecord, [recordId]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, T>> safeCall<T>(
    _i5.Future<T> Function()? operation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#safeCall, [operation]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, T>>.value(
              _FakeEither_0<_i6.Failure, T>(
                this,
                Invocation.method(#safeCall, [operation]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, T>>);
}

/// A class which mocks [WorkoutProgramRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutProgramRepository extends _i1.Mock
    implements _i8.WorkoutProgramRepository {
  MockWorkoutProgramRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i9.UserProgramModel>>>
  getUserPrograms(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPrograms, [userId]),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i9.UserProgramModel>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i9.UserProgramModel>>(
                    this,
                    Invocation.method(#getUserPrograms, [userId]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i9.UserProgramModel>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i9.UserProgramModel?>>
  getUserProgramDetails(String? userProgramId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProgramDetails, [userProgramId]),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, _i9.UserProgramModel?>
                >.value(
                  _FakeEither_0<_i6.Failure, _i9.UserProgramModel?>(
                    this,
                    Invocation.method(#getUserProgramDetails, [userProgramId]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i9.UserProgramModel?>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i10.UserProgramDayModel>>>
  getUserProgramDays(String? userProgramId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProgramDays, [userProgramId]),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i10.UserProgramDayModel>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i10.UserProgramDayModel>>(
                    this,
                    Invocation.method(#getUserProgramDays, [userProgramId]),
                  ),
                ),
          )
          as _i5.Future<
            _i2.Either<_i6.Failure, List<_i10.UserProgramDayModel>>
          >);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> updateUserProgramProgress(
    String? userProgramId,
    int? currentWeek,
    int? currentDay,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProgramProgress, [
              userProgramId,
              currentWeek,
              currentDay,
            ]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#updateUserProgramProgress, [
                  userProgramId,
                  currentWeek,
                  currentDay,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> completeUserProgramDay(
    String? userProgramId,
    int? week,
    int? day, {
    String? note,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #completeUserProgramDay,
              [userProgramId, week, day],
              {#note: note},
            ),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(
                  #completeUserProgramDay,
                  [userProgramId, week, day],
                  {#note: note},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> deleteUserProgram(
    String? userProgramId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserProgram, [userProgramId]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#deleteUserProgram, [userProgramId]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i11.CurrentWorkoutInfoModel>>
  getCurrentWorkoutInfo(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentWorkoutInfo, [userId]),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, _i11.CurrentWorkoutInfoModel>
                >.value(
                  _FakeEither_0<_i6.Failure, _i11.CurrentWorkoutInfoModel>(
                    this,
                    Invocation.method(#getCurrentWorkoutInfo, [userId]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i11.CurrentWorkoutInfoModel>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i9.UserProgramModel?>>
  getLatestActiveUserProgram(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestActiveUserProgram, [userId]),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, _i9.UserProgramModel?>
                >.value(
                  _FakeEither_0<_i6.Failure, _i9.UserProgramModel?>(
                    this,
                    Invocation.method(#getLatestActiveUserProgram, [userId]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i9.UserProgramModel?>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, T>> safeCall<T>(
    _i5.Future<T> Function()? operation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#safeCall, [operation]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, T>>.value(
              _FakeEither_0<_i6.Failure, T>(
                this,
                Invocation.method(#safeCall, [operation]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, T>>);
}

/// A class which mocks [WorkoutSessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutSessionRepository extends _i1.Mock
    implements _i12.WorkoutSessionRepository {
  MockWorkoutSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> createWorkoutSession({
    required String? userProgramId,
    required Map<String, dynamic>? exercisesJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createWorkoutSession, [], {
              #userProgramId: userProgramId,
              #exercisesJson: exercisesJson,
            }),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
              _FakeEither_0<_i6.Failure, String>(
                this,
                Invocation.method(#createWorkoutSession, [], {
                  #userProgramId: userProgramId,
                  #exercisesJson: exercisesJson,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.WorkoutSessionModel?>>
  getWorkoutSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutSession, [sessionId]),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, _i13.WorkoutSessionModel?>
                >.value(
                  _FakeEither_0<_i6.Failure, _i13.WorkoutSessionModel?>(
                    this,
                    Invocation.method(#getWorkoutSession, [sessionId]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i13.WorkoutSessionModel?>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i13.WorkoutSessionModel>>>
  getWorkoutSessions(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutSessions, [userId]),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i13.WorkoutSessionModel>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i13.WorkoutSessionModel>>(
                    this,
                    Invocation.method(#getWorkoutSessions, [userId]),
                  ),
                ),
          )
          as _i5.Future<
            _i2.Either<_i6.Failure, List<_i13.WorkoutSessionModel>>
          >);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i13.WorkoutSessionModel>>>
  getActiveWorkoutSessions(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveWorkoutSessions, [userId]),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i13.WorkoutSessionModel>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i13.WorkoutSessionModel>>(
                    this,
                    Invocation.method(#getActiveWorkoutSessions, [userId]),
                  ),
                ),
          )
          as _i5.Future<
            _i2.Either<_i6.Failure, List<_i13.WorkoutSessionModel>>
          >);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.WorkoutSessionModel>>
  updateWorkoutSession({
    required String? sessionId,
    required Map<String, dynamic>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkoutSession, [], {
              #sessionId: sessionId,
              #updates: updates,
            }),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, _i13.WorkoutSessionModel>
                >.value(
                  _FakeEither_0<_i6.Failure, _i13.WorkoutSessionModel>(
                    this,
                    Invocation.method(#updateWorkoutSession, [], {
                      #sessionId: sessionId,
                      #updates: updates,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i13.WorkoutSessionModel>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.WorkoutSessionModel>>
  completeWorkoutSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#completeWorkoutSession, [sessionId]),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, _i13.WorkoutSessionModel>
                >.value(
                  _FakeEither_0<_i6.Failure, _i13.WorkoutSessionModel>(
                    this,
                    Invocation.method(#completeWorkoutSession, [sessionId]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i13.WorkoutSessionModel>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> logWorkoutSet({
    required String? sessionId,
    required String? exerciseId,
    required int? setNumber,
    required int? reps,
    required double? weight,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logWorkoutSet, [], {
              #sessionId: sessionId,
              #exerciseId: exerciseId,
              #setNumber: setNumber,
              #reps: reps,
              #weight: weight,
            }),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#logWorkoutSet, [], {
                  #sessionId: sessionId,
                  #exerciseId: exerciseId,
                  #setNumber: setNumber,
                  #reps: reps,
                  #weight: weight,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, Map<String, dynamic>?>>
  getLastWorkoutLogByExercise({
    required String? exerciseId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLastWorkoutLogByExercise, [], {
              #exerciseId: exerciseId,
              #userId: userId,
            }),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, Map<String, dynamic>?>
                >.value(
                  _FakeEither_0<_i6.Failure, Map<String, dynamic>?>(
                    this,
                    Invocation.method(#getLastWorkoutLogByExercise, [], {
                      #exerciseId: exerciseId,
                      #userId: userId,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, Map<String, dynamic>?>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> getOrCreateExerciseId(
    String? exerciseName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateExerciseId, [exerciseName]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
              _FakeEither_0<_i6.Failure, String>(
                this,
                Invocation.method(#getOrCreateExerciseId, [exerciseName]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, T>> safeCall<T>(
    _i5.Future<T> Function()? operation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#safeCall, [operation]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, T>>.value(
              _FakeEither_0<_i6.Failure, T>(
                this,
                Invocation.method(#safeCall, [operation]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, T>>);
}

/// A class which mocks [DailySummaryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDailySummaryRepository extends _i1.Mock
    implements _i14.DailySummaryRepository {
  MockDailySummaryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i15.UserDailySummary?>> getDailySummary(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailySummary, [userId, date]),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, _i15.UserDailySummary?>
                >.value(
                  _FakeEither_0<_i6.Failure, _i15.UserDailySummary?>(
                    this,
                    Invocation.method(#getDailySummary, [userId, date]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i15.UserDailySummary?>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i15.UserDailySummary>> upsertDailySummary(
    _i15.UserDailySummary? summary,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsertDailySummary, [summary]),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, _i15.UserDailySummary>
                >.value(
                  _FakeEither_0<_i6.Failure, _i15.UserDailySummary>(
                    this,
                    Invocation.method(#upsertDailySummary, [summary]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i15.UserDailySummary>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i15.UserDailySummary>>>
  getDailySummariesForRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailySummariesForRange, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i15.UserDailySummary>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i15.UserDailySummary>>(
                    this,
                    Invocation.method(#getDailySummariesForRange, [
                      userId,
                      startDate,
                      endDate,
                    ]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i15.UserDailySummary>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i15.UserDailySummary>>
  calculateAndUpdateDailySummary(String? userId, DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#calculateAndUpdateDailySummary, [userId, date]),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, _i15.UserDailySummary>
                >.value(
                  _FakeEither_0<_i6.Failure, _i15.UserDailySummary>(
                    this,
                    Invocation.method(#calculateAndUpdateDailySummary, [
                      userId,
                      date,
                    ]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i15.UserDailySummary>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> deleteDailySummary(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDailySummary, [userId, date]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#deleteDailySummary, [userId, date]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, T>> safeCall<T>(
    _i5.Future<T> Function()? operation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#safeCall, [operation]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, T>>.value(
              _FakeEither_0<_i6.Failure, T>(
                this,
                Invocation.method(#safeCall, [operation]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, T>>);

  @override
  _i5.Future<bool> validateUserAccess(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#validateUserAccess, [userId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<T>>> getDataForDateRange<T>(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDataForDateRange, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, List<T>>>.value(
              _FakeEither_0<_i6.Failure, List<T>>(
                this,
                Invocation.method(#getDataForDateRange, [
                  userId,
                  startDate,
                  endDate,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<T>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<T>>> getDataForDate<T>(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDataForDate, [userId, date]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, List<T>>>.value(
              _FakeEither_0<_i6.Failure, List<T>>(
                this,
                Invocation.method(#getDataForDate, [userId, date]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<T>>>);
}

/// A class which mocks [ExerciseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRepository extends _i1.Mock
    implements _i16.ExerciseRepository {
  MockExerciseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>> search(
    String? query, {
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query], {#limit: limit}),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i17.Exercise>>(
                    this,
                    Invocation.method(#search, [query], {#limit: limit}),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>> searchWithFilters(
    String? query,
    Map<String, dynamic>? filters, {
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchWithFilters,
              [query, filters],
              {#limit: limit},
            ),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i17.Exercise>>(
                    this,
                    Invocation.method(
                      #searchWithFilters,
                      [query, filters],
                      {#limit: limit},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i17.Exercise?>> getExerciseById(
    String? exerciseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseById, [exerciseId]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i17.Exercise?>>.value(
                  _FakeEither_0<_i6.Failure, _i17.Exercise?>(
                    this,
                    Invocation.method(#getExerciseById, [exerciseId]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i17.Exercise?>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>> getExercisesByIds(
    List<String>? exerciseIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExercisesByIds, [exerciseIds]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i17.Exercise>>(
                    this,
                    Invocation.method(#getExercisesByIds, [exerciseIds]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>> getPopularExercises({
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPopularExercises, [], {#limit: limit}),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i17.Exercise>>(
                    this,
                    Invocation.method(#getPopularExercises, [], {
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>
  getExercisesByCategory(String? category, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getExercisesByCategory,
              [category],
              {#limit: limit},
            ),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i17.Exercise>>(
                    this,
                    Invocation.method(
                      #getExercisesByCategory,
                      [category],
                      {#limit: limit},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>
  getExercisesByMuscleGroup(String? muscleGroup, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getExercisesByMuscleGroup,
              [muscleGroup],
              {#limit: limit},
            ),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i17.Exercise>>(
                    this,
                    Invocation.method(
                      #getExercisesByMuscleGroup,
                      [muscleGroup],
                      {#limit: limit},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>
  getExercisesByEquipment(String? equipment, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getExercisesByEquipment,
              [equipment],
              {#limit: limit},
            ),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i17.Exercise>>(
                    this,
                    Invocation.method(
                      #getExercisesByEquipment,
                      [equipment],
                      {#limit: limit},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>
  getExercisesByDifficulty(String? difficulty, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getExercisesByDifficulty,
              [difficulty],
              {#limit: limit},
            ),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i17.Exercise>>(
                    this,
                    Invocation.method(
                      #getExercisesByDifficulty,
                      [difficulty],
                      {#limit: limit},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<String>>> getExerciseCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseCategories, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<String>>>.value(
                  _FakeEither_0<_i6.Failure, List<String>>(
                    this,
                    Invocation.method(#getExerciseCategories, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<String>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<String>>> getMuscleGroups() =>
      (super.noSuchMethod(
            Invocation.method(#getMuscleGroups, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<String>>>.value(
                  _FakeEither_0<_i6.Failure, List<String>>(
                    this,
                    Invocation.method(#getMuscleGroups, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<String>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<String>>> getEquipmentTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getEquipmentTypes, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<String>>>.value(
                  _FakeEither_0<_i6.Failure, List<String>>(
                    this,
                    Invocation.method(#getEquipmentTypes, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<String>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<String>>> getDifficultyLevels() =>
      (super.noSuchMethod(
            Invocation.method(#getDifficultyLevels, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<String>>>.value(
                  _FakeEither_0<_i6.Failure, List<String>>(
                    this,
                    Invocation.method(#getDifficultyLevels, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<String>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#clearCache, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> refreshCache() =>
      (super.noSuchMethod(
            Invocation.method(#refreshCache, []),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#refreshCache, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, T>> safeCall<T>(
    _i5.Future<T> Function()? operation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#safeCall, [operation]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, T>>.value(
              _FakeEither_0<_i6.Failure, T>(
                this,
                Invocation.method(#safeCall, [operation]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, T>>);
}

/// A class which mocks [AuthBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthBloc extends _i1.Mock implements _i18.AuthBloc {
  MockAuthBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAuthState_1(this, Invocation.getter(#state)),
          )
          as _i3.AuthState);

  @override
  _i5.Stream<_i3.AuthState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i3.AuthState>.empty(),
          )
          as _i5.Stream<_i3.AuthState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void add(_i19.AuthEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i19.AuthEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.AuthState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i19.AuthEvent>(
    _i20.EventHandler<E, _i3.AuthState>? handler, {
    _i20.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i20.Transition<_i19.AuthEvent, _i3.AuthState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i20.Change<_i3.AuthState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
