// Mocks generated by Mockito 5.4.6 from annotations
// in jfit/test/integration/workout_program_logging_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:jfit/core/error/failures.dart' as _i5;
import 'package:jfit/features/programs/data/models/user_program_day_model.dart'
    as _i7;
import 'package:jfit/features/workout_program/data/models/current_workout_info_model.dart'
    as _i8;
import 'package:jfit/features/workout_program/data/models/user_program_model.dart'
    as _i6;
import 'package:jfit/features/workout_program/data/repositories/workout_program_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WorkoutProgramRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutProgramRepository extends _i1.Mock
    implements _i3.WorkoutProgramRepository {
  MockWorkoutProgramRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.UserProgramModel>>>
  getUserPrograms(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPrograms, [userId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.UserProgramModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.UserProgramModel>>(
                    this,
                    Invocation.method(#getUserPrograms, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.UserProgramModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserProgramModel?>>
  getUserProgramDetails(String? userProgramId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProgramDetails, [userProgramId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.UserProgramModel?>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.UserProgramModel?>(
                    this,
                    Invocation.method(#getUserProgramDetails, [userProgramId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.UserProgramModel?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserProgramDayModel>>>
  getUserProgramDays(String? userProgramId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProgramDays, [userProgramId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i7.UserProgramDayModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i7.UserProgramDayModel>>(
                    this,
                    Invocation.method(#getUserProgramDays, [userProgramId]),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.Failure, List<_i7.UserProgramDayModel>>
          >);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateUserProgramProgress(
    String? userProgramId,
    int? currentWeek,
    int? currentDay,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProgramProgress, [
              userProgramId,
              currentWeek,
              currentDay,
            ]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateUserProgramProgress, [
                  userProgramId,
                  currentWeek,
                  currentDay,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> completeUserProgramDay(
    String? userProgramId,
    int? week,
    int? day, {
    String? note,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #completeUserProgramDay,
              [userProgramId, week, day],
              {#note: note},
            ),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(
                  #completeUserProgramDay,
                  [userProgramId, week, day],
                  {#note: note},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteUserProgram(
    String? userProgramId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserProgram, [userProgramId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteUserProgram, [userProgramId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.CurrentWorkoutInfoModel>>
  getCurrentWorkoutInfo(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentWorkoutInfo, [userId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i8.CurrentWorkoutInfoModel>
                >.value(
                  _FakeEither_0<_i5.Failure, _i8.CurrentWorkoutInfoModel>(
                    this,
                    Invocation.method(#getCurrentWorkoutInfo, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.CurrentWorkoutInfoModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserProgramModel?>>
  getLatestActiveUserProgram(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestActiveUserProgram, [userId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.UserProgramModel?>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.UserProgramModel?>(
                    this,
                    Invocation.method(#getLatestActiveUserProgram, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.UserProgramModel?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, T>> safeCall<T>(
    _i4.Future<T> Function()? operation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#safeCall, [operation]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, T>>.value(
              _FakeEither_0<_i5.Failure, T>(
                this,
                Invocation.method(#safeCall, [operation]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, T>>);
}
